; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/auditreduce-crash.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs < %s | FileCheck %s --check-prefix=PURECAP
;; Hybrid baseline to compare against
; RUN: sed 's/addrspace(200)//g' %s | llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -verify-machineinstrs | FileCheck %s --check-prefix=HYBRID

%struct.au_mask = type {}
%struct.tokenstr = type { i8, ptr, i64, %union.anon }
%union.anon = type { %struct.au_execarg_t }
%struct.au_execarg_t = type { i32, [128 x ptr addrspace(200)] }

@maskp = external addrspace(200) global %struct.au_mask

define i32 @select_hdr32(ptr addrspace(200) byval(%struct.tokenstr) %0, ptr addrspace(200) %optchkd) nounwind {
; PURECAP-LABEL: select_hdr32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-NEXT:    clh a0, 0(a0)
; PURECAP-NEXT:  .LBB0_1: # %entry
; PURECAP-NEXT:    # Label of block must be emitted
; PURECAP-NEXT:    auipcc a1, %got_pcrel_hi(maskp)
; PURECAP-NEXT:    clc a1, %pcrel_lo(.LBB0_1)(a1)
; PURECAP-NEXT:    li a2, 3
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall au_preselect
; PURECAP-NEXT:    li a0, 0
; PURECAP-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: select_hdr32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lh a0, 0(a0)
; HYBRID-NEXT:  .Lpcrel_hi0:
; HYBRID-NEXT:    auipc a1, %got_pcrel_hi(maskp)
; HYBRID-NEXT:    ld a1, %pcrel_lo(.Lpcrel_hi0)(a1)
; HYBRID-NEXT:    li a2, 3
; HYBRID-NEXT:    li a3, 0
; HYBRID-NEXT:    call au_preselect
; HYBRID-NEXT:    li a0, 0
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
entry:
  %1 = getelementptr %struct.tokenstr, ptr addrspace(200) %0, i64 0, i32 0
  %tok.sroa.1.0..sroa_idx = getelementptr i8, ptr addrspace(200) %1
  %tok.sroa.1.0..sroa_cast = bitcast ptr addrspace(200) %tok.sroa.1.0..sroa_idx to ptr addrspace(200)
  %tok.sroa.1.0.copyload = load i16, ptr addrspace(200) %tok.sroa.1.0..sroa_cast, align 2
  %call26 = call i32 @au_preselect(i16 %tok.sroa.1.0.copyload, ptr addrspace(200) @maskp, i32 3, i32 0)
  ret i32 0
}

define i32 @foo(ptr addrspace(200) byval(i512) %x, ptr addrspace(200) byval(%struct.tokenstr) %0, ptr addrspace(200) %optchkd) nounwind {
; PURECAP-LABEL: foo:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-NEXT:    clh a0, 0(a1)
; PURECAP-NEXT:  .LBB1_1: # %entry
; PURECAP-NEXT:    # Label of block must be emitted
; PURECAP-NEXT:    auipcc a1, %got_pcrel_hi(maskp)
; PURECAP-NEXT:    clc a1, %pcrel_lo(.LBB1_1)(a1)
; PURECAP-NEXT:    li a2, 3
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall au_preselect
; PURECAP-NEXT:    li a0, 0
; PURECAP-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: foo:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lh a0, 0(a1)
; HYBRID-NEXT:  .Lpcrel_hi1:
; HYBRID-NEXT:    auipc a1, %got_pcrel_hi(maskp)
; HYBRID-NEXT:    ld a1, %pcrel_lo(.Lpcrel_hi1)(a1)
; HYBRID-NEXT:    li a2, 3
; HYBRID-NEXT:    li a3, 0
; HYBRID-NEXT:    call au_preselect
; HYBRID-NEXT:    li a0, 0
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
entry:
  %1 = getelementptr %struct.tokenstr, ptr addrspace(200) %0, i64 0, i32 0
  %tok.sroa.1.0..sroa_idx = getelementptr i8, ptr addrspace(200) %1
  %tok.sroa.1.0..sroa_cast = bitcast ptr addrspace(200) %tok.sroa.1.0..sroa_idx to ptr addrspace(200)
  %tok.sroa.1.0.copyload = load i16, ptr addrspace(200) %tok.sroa.1.0..sroa_cast, align 2
  %call26 = call i32 @au_preselect(i16 %tok.sroa.1.0.copyload, ptr addrspace(200) @maskp, i32 3, i32 0)
  ret i32 0
}

declare i32 @au_preselect(i16 signext, ptr addrspace(200), i32, i32)
