; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-byval-argument-varargs.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP
; we should really be getting an error when compiling this with the hybrid ABI (alloca in AS 200)
; RUNTODO: not llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d < %s 2>&1 | FileCheck %s -check-prefix BAD-ABI
; BAD-ABI: error: abc

%struct.Dwarf_Error = type { [1024 x i32] }

@a = common local_unnamed_addr addrspace(200) global %struct.Dwarf_Error zeroinitializer, align 4

; Function Attrs: nounwind
define i32 @fn1() local_unnamed_addr #0 {
; PURECAP-LABEL: fn1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -2032
; PURECAP-NEXT:    csc ra, 2016(sp) # 16-byte Folded Spill
; PURECAP-NEXT:    csc s0, 2000(sp) # 16-byte Folded Spill
; PURECAP-NEXT:    csc s1, 1984(sp) # 16-byte Folded Spill
; PURECAP-NEXT:    lui a0, 1048574
; PURECAP-NEXT:    addi a0, a0, 1952
; PURECAP-NEXT:    cincoffset sp, sp, a0
; PURECAP-NEXT:    lui a0, 1
; PURECAP-NEXT:    lui a1, 1
; PURECAP-NEXT:    cincoffset a1, sp, a1
; PURECAP-NEXT:    cincoffset a1, a1, 32
; PURECAP-NEXT:    csetbounds s0, a1, a0
; PURECAP-NEXT:  .LBB0_1: # %entry
; PURECAP-NEXT:    # Label of block must be emitted
; PURECAP-NEXT:    auipcc a1, %got_pcrel_hi(a)
; PURECAP-NEXT:    clc a1, %pcrel_lo(.LBB0_1)(a1)
; PURECAP-NEXT:    lui a2, 1
; PURECAP-NEXT:    cmove a0, s0
; PURECAP-NEXT:    ccall memcpy
; PURECAP-NEXT:    cincoffset a0, sp, 32
; PURECAP-NEXT:    lui a2, 1
; PURECAP-NEXT:    cincoffset s1, sp, 32
; PURECAP-NEXT:    cmove a1, s0
; PURECAP-NEXT:    ccall memcpy
; PURECAP-NEXT:    csc s1, 0(sp)
; PURECAP-NEXT:    ccall fn2
; PURECAP-NEXT:    lui a0, 2
; PURECAP-NEXT:    addi a0, a0, -1952
; PURECAP-NEXT:    cincoffset sp, sp, a0
; PURECAP-NEXT:    clc ra, 2016(sp) # 16-byte Folded Reload
; PURECAP-NEXT:    clc s0, 2000(sp) # 16-byte Folded Reload
; PURECAP-NEXT:    clc s1, 1984(sp) # 16-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 2032
; PURECAP-NEXT:    cret
entry:
  %tmp = alloca %struct.Dwarf_Error, align 8, addrspace(200)
  %0 = bitcast ptr addrspace(200) %tmp to ptr addrspace(200)
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) nonnull align 4 %0, ptr addrspace(200) align 4 @a, i64 4096, i1 false)
  %call = call i32 (...) @fn2(ptr addrspace(200) nonnull byval(%struct.Dwarf_Error) align 8 %tmp) #0
  ret i32 undef
}

; Function Attrs: nounwind
declare i32 @fn2(...) #0

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg) #1

attributes #0 = { nounwind }
attributes #1 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
