; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-purecap-vaargs.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -O1 %s -o - | FileCheck %s --check-prefix=PURECAP

@va_copy = common addrspace(200) global ptr addrspace(200) null, align 16

define void @copy_to_global(ptr addrspace(200) nocapture readnone %y, i32 signext %x, ...) addrspace(200) nounwind {
; PURECAP-LABEL: copy_to_global:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    cincoffset a0, sp, 0
; PURECAP-NEXT:  .LBB0_1: # Label of block must be emitted
; PURECAP-NEXT:    auipcc a1, %got_pcrel_hi(va_copy)
; PURECAP-NEXT:    clc a1, %pcrel_lo(.LBB0_1)(a1)
; PURECAP-NEXT:    csetbounds a0, a0, 16
; PURECAP-NEXT:    cincoffset a2, sp, 16
; PURECAP-NEXT:    csc a2, 0(a0)
; PURECAP-NEXT:    csc a2, 0(a1)
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
  %1 = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.va_start.p200(ptr addrspace(200) %1)
  call void @llvm.va_copy.p200.p200(ptr addrspace(200) @va_copy, ptr addrspace(200) %1)
  call void @llvm.va_end.p200(ptr addrspace(200) %1)
  ret void
}

define ptr addrspace(200) @copy_from_global() addrspace(200) nounwind {
; PURECAP-LABEL: copy_from_global:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:  .LBB1_1: # Label of block must be emitted
; PURECAP-NEXT:    auipcc a0, %got_pcrel_hi(va_copy)
; PURECAP-NEXT:    clc a0, %pcrel_lo(.LBB1_1)(a0)
; PURECAP-NEXT:    clc a0, 0(a0)
; PURECAP-NEXT:    cincoffset a1, sp, 0
; PURECAP-NEXT:    csetbounds a1, a1, 16
; PURECAP-NEXT:    csc a0, 0(a1)
; PURECAP-NEXT:    clc a0, 0(sp)
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
  %1 = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.va_copy.p200.p200(ptr addrspace(200) %1, ptr addrspace(200) @va_copy)
  %2 = load ptr addrspace(200), ptr addrspace(200) %1, align 16
  ret ptr addrspace(200) %2
}

declare void @llvm.va_start.p200(ptr addrspace(200)) addrspace(200)
declare void @llvm.va_copy.p200.p200(ptr addrspace(200), ptr addrspace(200)) addrspace(200)
declare void @llvm.va_end.p200(ptr addrspace(200)) addrspace(200)
