; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-float.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d %s -o - | FileCheck %s --check-prefix=PURECAP

; Function Attrs: nounwind memory(read)
define double @load64(ptr addrspace(200) nocapture readonly %x) #0 {
; HYBRID-LABEL: load64:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    ld.cap a0, (a0)
; HYBRID-NEXT:    fmv.d.x fa0, a0
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: load64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cfld fa0, 0(a0)
; PURECAP-NEXT:    cret
entry:
  %0 = load double, ptr addrspace(200) %x, align 8
  ret double %0
}

; Function Attrs: nounwind memory(read)
define float @load32(ptr addrspace(200) nocapture readonly %x) #0 {
; HYBRID-LABEL: load32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lw.cap a0, (a0)
; HYBRID-NEXT:    fmv.w.x fa0, a0
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: load32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cflw fa0, 0(a0)
; PURECAP-NEXT:    cret
entry:
  %0 = load float, ptr addrspace(200) %x, align 4
  ret float %0
}

; Function Attrs: nounwind
define void @store64(ptr addrspace(200) nocapture %x, double %y) #1 {
; HYBRID-LABEL: store64:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    fmv.x.d a1, fa0
; HYBRID-NEXT:    sd.cap a1, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: store64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cfsd fa0, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store double %y, ptr addrspace(200) %x, align 8
  ret void
}

; Function Attrs: nounwind
define void @store32(ptr addrspace(200) nocapture %x, float %y) #1 {
; HYBRID-LABEL: store32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    fmv.x.w a1, fa0
; HYBRID-NEXT:    sw.cap a1, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: store32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cfsw fa0, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store float %y, ptr addrspace(200) %x, align 4
  ret void
}

attributes #0 = { nounwind }
attributes #1 = { nounwind "use-soft-float"="false" }
