; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cincoffset-immediate.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP

define ptr addrspace(200) @imm(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: imm:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset a0, a0, 1023
; PURECAP-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1023
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @imm1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: imm1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset a0, a0, -1024
; PURECAP-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1024
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: reg:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset a0, a0, 1024
; PURECAP-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1024
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: reg1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset a0, a0, -1025
; PURECAP-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1025
  ret ptr addrspace(200) %add.ptr
}
