; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-store-cap.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d %s -o - | FileCheck %s --check-prefix=HYBRID

@n = common global ptr addrspace(200) null, align 32

define void @set(ptr addrspace(200) %h) nounwind {
; HYBRID-LABEL: set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:  .Lpcrel_hi0:
; HYBRID-NEXT:    auipc a1, %got_pcrel_hi(n)
; HYBRID-NEXT:    ld a1, %pcrel_lo(.Lpcrel_hi0)(a1)
; HYBRID-NEXT:    lc a1, 0(a1)
; HYBRID-NEXT:    sc.cap a0, (a1)
; HYBRID-NEXT:    ret
  %1 = load ptr addrspace(200), ptr @n, align 32
  store ptr addrspace(200) %h, ptr addrspace(200) %1, align 32
  ret void
}
