; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-stack-variable.ll
;; Check the cap-typed @llvm.stacksave.p200 / @llvm.stackrestore.p200
;; intrinsics around a VLA inside a loop, ensuring the saved cap stack
;; pointer is restored each iteration so the stack does not grow without
;; bound.
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -O1 %s -o - | FileCheck %s --check-prefix=CHECK

define void @dynamic_alloca(i32 signext %x) local_unnamed_addr nounwind {
; CHECK-LABEL: dynamic_alloca:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    blez a0, .LBB0_4
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    cincoffset sp, sp, -112
; CHECK-NEXT:    csc ra, 96(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s0, 80(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s1, 64(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s2, 48(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s3, 32(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s4, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s5, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset s0, sp, 112
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    slli s2, a0, 2
; CHECK-NEXT:    addi a0, s2, 15
; CHECK-NEXT:    andi a0, a0, -16
; CHECK-NEXT:    crrl s3, a0
; CHECK-NEXT:    cram s4, a0
; CHECK-NEXT:  .LBB0_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmove s5, sp
; CHECK-NEXT:    sub a0, sp, s3
; CHECK-NEXT:    and a0, a0, s4
; CHECK-NEXT:    csetaddr a0, sp, a0
; CHECK-NEXT:    csetbounds a1, a0, s3
; CHECK-NEXT:    cmove sp, a0
; CHECK-NEXT:    csetbounds a0, a1, s2
; CHECK-NEXT:    ccall use_arg
; CHECK-NEXT:    cmove sp, s5
; CHECK-NEXT:    addiw s1, s1, -1
; CHECK-NEXT:    bnez s1, .LBB0_2
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    cincoffset sp, s0, -112
; CHECK-NEXT:    clc ra, 96(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s0, 80(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s1, 64(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s2, 48(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s3, 32(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s4, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s5, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 112
; CHECK-NEXT:  .LBB0_4: # %for.cond.cleanup
; CHECK-NEXT:    cret
entry:
  %cmp4 = icmp sgt i32 %x, 0
  br i1 %cmp4, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %0 = zext i32 %x to i64
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.05 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %1 = call ptr addrspace(200) @llvm.stacksave.p200()
  %vla = alloca i32, i64 %0, align 4, addrspace(200)
  call void @use_arg(ptr addrspace(200) nonnull %vla)
  call void @llvm.stackrestore.p200(ptr addrspace(200) %1)
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond = icmp eq i32 %inc, %x
  br i1 %exitcond, label %for.cond.cleanup, label %for.body
}

; Function Attrs: nounwind
declare void @use_arg(ptr addrspace(200)) nounwind

declare ptr addrspace(200) @llvm.stacksave.p200()

declare void @llvm.stackrestore.p200(ptr addrspace(200))
