; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memcpy-webkit-overlapping-tag-cleared.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d %s -o - -O2 -verify-machineinstrs | FileCheck %s
; Regression test for a crash in Webkit where the tag bit for hash map keys was cleared due to
; inlined memcpy performing an unaligned csd that cleared the tag bit of the key member


declare void @llvm.lifetime.start.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)

declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg) addrspace(200)

declare void @llvm.lifetime.end.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)

declare ptr addrspace(200) @find_in_table(i32 signext) local_unnamed_addr addrspace(200) nounwind

define i1 @insert_padded_test(ptr addrspace(200) nocapture readonly %key, i32 signext %index) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: insert_padded_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -32
; CHECK-NEXT:    csc ra, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s0, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    cmove s0, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ccall find_in_table
; CHECK-NEXT:    clc a2, 0(s0)
; CHECK-NEXT:    cmove a1, a0
; CHECK-NEXT:    csc a2, 0(a0)
; CHECK-NEXT:    clc a2, 16(s0)
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    csc a2, 16(a1)
; CHECK-NEXT:    clc ra, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s0, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 32
; CHECK-NEXT:    cret
entry:
  %call = tail call ptr addrspace(200) @find_in_table(i32 signext %index) nounwind
  %0 = bitcast ptr addrspace(200) %call to ptr addrspace(200)
  %1 = bitcast ptr addrspace(200) %key to ptr addrspace(200)
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %0, ptr addrspace(200) nonnull align 16 %1, i64 32, i1 false)
  ret i1 true
}

; Ensure that we don't attempt to perfom a CIncOffset by 14 followed by an 8byte store for the last few bytes
; This was preivoulsy clearing the tag bit. Perform a 4 byte store followed by a 2 byte one instead!
define i1 @insert_padded_but_copy_only_relevant_bytes(ptr addrspace(200) nocapture readonly %key, i32 signext %index) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: insert_padded_but_copy_only_relevant_bytes:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -32
; CHECK-NEXT:    csc ra, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s0, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    cmove s0, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ccall find_in_table
; CHECK-NEXT:    clc a2, 0(s0)
; CHECK-NEXT:    cmove a1, a0
; CHECK-NEXT:    csc a2, 0(a0)
; CHECK-NEXT:    clc a2, 16(s0)
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    csc a2, 16(a1)
; CHECK-NEXT:    clc ra, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s0, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 32
; CHECK-NEXT:    cret
entry:
  %call = tail call ptr addrspace(200) @find_in_table(i32 signext %index) nounwind
  %0 = bitcast ptr addrspace(200) %call to ptr addrspace(200)
  %1 = bitcast ptr addrspace(200) %key to ptr addrspace(200)
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %0, ptr addrspace(200) nonnull align 16 %1, i64 32, i1 false)
  ret i1 true
}

declare ptr addrspace(200) @find_in_table_unpadded(i32 signext) local_unnamed_addr addrspace(200) nounwind

define i1 @insert_no_padding(ptr addrspace(200) nocapture readonly %key, i32 signext %index) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: insert_no_padding:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -32
; CHECK-NEXT:    csc ra, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s0, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    cmove s0, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ccall find_in_table_unpadded
; CHECK-NEXT:    clc a2, 0(s0)
; CHECK-NEXT:    cmove a1, a0
; CHECK-NEXT:    csc a2, 0(a0)
; CHECK-NEXT:    clw a0, 16(s0)
; CHECK-NEXT:    csw a0, 16(a1)
; CHECK-NEXT:    clh a2, 20(s0)
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    csh a2, 20(a1)
; CHECK-NEXT:    clc ra, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s0, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 32
; CHECK-NEXT:    cret
entry:
  %call = tail call ptr addrspace(200) @find_in_table_unpadded(i32 signext %index) nounwind
  %0 = bitcast ptr addrspace(200) %call to ptr addrspace(200)
  %1 = bitcast ptr addrspace(200) %key to ptr addrspace(200)
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %0, ptr addrspace(200) nonnull align 16 %1, i64 22, i1 false)
  ret i1 true
}
