; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/mempcpy.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs %s -o - -O2 | FileCheck %s

define ptr addrspace(200) @wrap_mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n) nounwind {
; CHECK-LABEL: wrap_mempcpy:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset sp, sp, -48
; CHECK-NEXT:    csc ra, 32(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s0, 16(sp) # 16-byte Folded Spill
; CHECK-NEXT:    csc s1, 0(sp) # 16-byte Folded Spill
; CHECK-NEXT:    mv s0, a2
; CHECK-NEXT:    cmove s1, a0
; CHECK-NEXT:    ccall memcpy
; CHECK-NEXT:    cincoffset a0, s1, s0
; CHECK-NEXT:    clc ra, 32(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s0, 16(sp) # 16-byte Folded Reload
; CHECK-NEXT:    clc s1, 0(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 48
; CHECK-NEXT:    cret
  %1 = tail call ptr addrspace(200) @mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n)
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @mempcpy(ptr addrspace(200), ptr addrspace(200), i64)
