; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memset-type.ll
; Check the element type chosen when expanding a memset of a capability-aligned
; buffer: a zero memset can use capability stores of the null capability, but a
; non-zero memset cannot, so it uses the generic expansion (inline integer
; stores on 128-bit-cap targets, a library call on RV32).
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs -O1 %s -o - | FileCheck %s -check-prefix=CHECK

declare void @llvm.memset.p200.i64(ptr addrspace(200) nocapture writeonly, i8, i64, i1 immarg) addrspace(200)

; Check that the zero memset is expanded to capability stores + a single tail store.
define void @align64(ptr addrspace(200) nocapture %out) addrspace(200) {
; CHECK-LABEL: align64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    csw zero, 32(a0)
; CHECK-NEXT:    csc zero, 16(a0)
; CHECK-NEXT:    csc zero, 0(a0)
; CHECK-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 64 %out, i8 0, i64 36, i1 false)
  ret void
}

; Can't use capability stores for a non-zero fill, so fall back to the generic
; expansion (inline integer stores here, a library call on RV32).
define void @align64_nonzero_value(ptr addrspace(200) nocapture %out) addrspace(200) {
; CHECK-LABEL: align64_nonzero_value:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a1, 4112
; CHECK-NEXT:    addi a1, a1, 257
; CHECK-NEXT:    slli a2, a1, 32
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    csw a1, 32(a0)
; CHECK-NEXT:    csd a1, 24(a0)
; CHECK-NEXT:    csd a1, 16(a0)
; CHECK-NEXT:    csd a1, 8(a0)
; CHECK-NEXT:    csd a1, 0(a0)
; CHECK-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 64 %out, i8 1, i64 36, i1 false)
  ret void
}
