; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/rust.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -verify-machineinstrs %s -o - | FileCheck %s

;; Crash found while compiling rust-generated code:
declare { ptr addrspace(200), ptr addrspace(200), ptr addrspace(200) } @"_ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE"(ptr addrspace(200), i128) addrspace(200)

define void @a() nounwind {
; CHECK-LABEL: a:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset sp, sp, -64
; CHECK-NEXT:    csc ra, 48(sp) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset a0, sp, 0
; CHECK-NEXT:    li a2, 6
; CHECK-NEXT:    cmove a1, zero
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    ccall _ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE
; CHECK-NEXT:    clc ra, 48(sp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 64
; CHECK-NEXT:    cret
  %1 = call { ptr addrspace(200), ptr addrspace(200), ptr addrspace(200) } @"_ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE"(ptr addrspace(200) null, i128 6)
  ret void
}
