; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/auditreduce-crash.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs < %s | FileCheck %s --check-prefix=PURECAP
;; Hybrid baseline to compare against
; RUN: sed 's/addrspace(200)//g' %s | llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -verify-machineinstrs | FileCheck %s --check-prefix=HYBRID

%struct.au_mask = type {}
%struct.tokenstr = type { i8, ptr, i64, %union.anon }
%union.anon = type { %struct.au_execarg_t }
%struct.au_execarg_t = type { i32, [128 x ptr addrspace(200)] }

@maskp = external addrspace(200) global %struct.au_mask

define i32 @select_hdr32(ptr addrspace(200) byval(%struct.tokenstr) %0, ptr addrspace(200) %optchkd) nounwind {
; PURECAP-LABEL: select_hdr32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset $c11, $c11, -16
; PURECAP-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    clh $4, $zero, 16($c11)
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    clcbi $c3, %captab20(maskp)($c1)
; PURECAP-NEXT:    clcbi $c12, %capcall20(au_preselect)($c1)
; PURECAP-NEXT:    daddiu $5, $zero, 3
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    daddiu $6, $zero, 0
; PURECAP-NEXT:    addiu $2, $zero, 0
; PURECAP-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 16
;
; HYBRID-LABEL: select_hdr32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $sp, $sp, -80
; HYBRID-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $gp, 0($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lui $1, %hi(%neg(%gp_rel(select_hdr32)))
; HYBRID-NEXT:    daddu $1, $1, $25
; HYBRID-NEXT:    daddiu $gp, $1, %lo(%neg(%gp_rel(select_hdr32)))
; HYBRID-NEXT:    sd $11, 72($sp)
; HYBRID-NEXT:    sd $10, 64($sp)
; HYBRID-NEXT:    sd $9, 56($sp)
; HYBRID-NEXT:    sd $8, 48($sp)
; HYBRID-NEXT:    sd $7, 40($sp)
; HYBRID-NEXT:    sd $6, 32($sp)
; HYBRID-NEXT:    sd $5, 24($sp)
; HYBRID-NEXT:    sd $4, 16($sp)
; HYBRID-NEXT:    dsra $4, $4, 48
; HYBRID-NEXT:    ld $5, %got_disp(maskp)($gp)
; HYBRID-NEXT:    ld $25, %call16(au_preselect)($gp)
; HYBRID-NEXT:    daddiu $6, $zero, 3
; HYBRID-NEXT:    .reloc .Ltmp0, R_MIPS_JALR, au_preselect
; HYBRID-NEXT:  .Ltmp0:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    daddiu $7, $zero, 0
; HYBRID-NEXT:    addiu $2, $zero, 0
; HYBRID-NEXT:    ld $gp, 0($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $sp, $sp, 80
entry:
  %1 = getelementptr %struct.tokenstr, ptr addrspace(200) %0, i64 0, i32 0
  %tok.sroa.1.0..sroa_idx = getelementptr i8, ptr addrspace(200) %1
  %tok.sroa.1.0..sroa_cast = bitcast ptr addrspace(200) %tok.sroa.1.0..sroa_idx to ptr addrspace(200)
  %tok.sroa.1.0.copyload = load i16, ptr addrspace(200) %tok.sroa.1.0..sroa_cast, align 2
  %call26 = call i32 @au_preselect(i16 %tok.sroa.1.0.copyload, ptr addrspace(200) @maskp, i32 3, i32 0)
  ret i32 0
}

define i32 @foo(ptr addrspace(200) byval(i512) %x, ptr addrspace(200) byval(%struct.tokenstr) %0, ptr addrspace(200) %optchkd) nounwind {
; PURECAP-LABEL: foo:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset $c11, $c11, -32
; PURECAP-NEXT:    csc $c17, $zero, 16($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    clh $4, $zero, 96($c11)
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    clcbi $c3, %captab20(maskp)($c1)
; PURECAP-NEXT:    clcbi $c12, %capcall20(au_preselect)($c1)
; PURECAP-NEXT:    daddiu $5, $zero, 3
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    daddiu $6, $zero, 0
; PURECAP-NEXT:    addiu $2, $zero, 0
; PURECAP-NEXT:    clc $c17, $zero, 16($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 32
;
; HYBRID-LABEL: foo:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $sp, $sp, -80
; HYBRID-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $gp, 0($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lui $1, %hi(%neg(%gp_rel(foo)))
; HYBRID-NEXT:    daddu $1, $1, $25
; HYBRID-NEXT:    daddiu $gp, $1, %lo(%neg(%gp_rel(foo)))
; HYBRID-NEXT:    sd $11, 72($sp)
; HYBRID-NEXT:    sd $10, 64($sp)
; HYBRID-NEXT:    sd $9, 56($sp)
; HYBRID-NEXT:    sd $8, 48($sp)
; HYBRID-NEXT:    sd $7, 40($sp)
; HYBRID-NEXT:    sd $6, 32($sp)
; HYBRID-NEXT:    lh $1, 80($sp)
; HYBRID-NEXT:    sd $5, 24($sp)
; HYBRID-NEXT:    sd $4, 16($sp)
; HYBRID-NEXT:    ld $5, %got_disp(maskp)($gp)
; HYBRID-NEXT:    ld $25, %call16(au_preselect)($gp)
; HYBRID-NEXT:    daddiu $6, $zero, 3
; HYBRID-NEXT:    daddiu $7, $zero, 0
; HYBRID-NEXT:    .reloc .Ltmp1, R_MIPS_JALR, au_preselect
; HYBRID-NEXT:  .Ltmp1:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    move $4, $1
; HYBRID-NEXT:    addiu $2, $zero, 0
; HYBRID-NEXT:    ld $gp, 0($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $ra, 8($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $sp, $sp, 80
entry:
  %1 = getelementptr %struct.tokenstr, ptr addrspace(200) %0, i64 0, i32 0
  %tok.sroa.1.0..sroa_idx = getelementptr i8, ptr addrspace(200) %1
  %tok.sroa.1.0..sroa_cast = bitcast ptr addrspace(200) %tok.sroa.1.0..sroa_idx to ptr addrspace(200)
  %tok.sroa.1.0.copyload = load i16, ptr addrspace(200) %tok.sroa.1.0..sroa_cast, align 2
  %call26 = call i32 @au_preselect(i16 %tok.sroa.1.0.copyload, ptr addrspace(200) @maskp, i32 3, i32 0)
  ret i32 0
}

declare i32 @au_preselect(i16 signext, ptr addrspace(200), i32, i32)
