; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/bzerocap.ll
;; This test assumes cheri128, since on 256 a 16 byte aligned pointer won't be expanded
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -O1 %s -o - | FileCheck %s --check-prefix=PURECAP

define void @zero64(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 64, i1 false)
  ret void
}

define void @zero64_unaligned(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero64_unaligned:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csd $zero, $zero, 0($c3)
; PURECAP-NEXT:    csd $zero, $zero, 56($c3)
; PURECAP-NEXT:    csd $zero, $zero, 48($c3)
; PURECAP-NEXT:    csd $zero, $zero, 40($c3)
; PURECAP-NEXT:    csd $zero, $zero, 32($c3)
; PURECAP-NEXT:    csd $zero, $zero, 24($c3)
; PURECAP-NEXT:    csd $zero, $zero, 16($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csd $zero, $zero, 8($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 8 %out, i8 0, i64 64, i1 false)
  ret void
}

define void @zero65(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero65:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 65, i1 false)
  ret void
}

define void @zero66(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero66:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csh $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 66, i1 false)
  ret void
}

define void @zero67(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero67:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 66($c3)
; PURECAP-NEXT:    csh $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 67, i1 false)
  ret void
}

define void @zero68(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero68:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csw $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 68, i1 false)
  ret void
}

define void @zero69(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero69:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 68($c3)
; PURECAP-NEXT:    csw $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 69, i1 false)
  ret void
}

define void @zero70(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero70:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csh $zero, $zero, 68($c3)
; PURECAP-NEXT:    csw $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 70, i1 false)
  ret void
}

define void @zero71(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero71:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 70($c3)
; PURECAP-NEXT:    csh $zero, $zero, 68($c3)
; PURECAP-NEXT:    csw $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 71, i1 false)
  ret void
}

define void @zero72(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero72:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 72, i1 false)
  ret void
}

define void @zero73(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero73:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 73, i1 false)
  ret void
}

define void @zero74(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero74:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csh $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 74, i1 false)
  ret void
}

define void @zero75(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero75:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 74($c3)
; PURECAP-NEXT:    csh $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 75, i1 false)
  ret void
}

define void @zero76(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero76:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csw $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 76, i1 false)
  ret void
}

define void @zero77(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero77:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 76($c3)
; PURECAP-NEXT:    csw $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 77, i1 false)
  ret void
}

define void @zero78(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero78:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csh $zero, $zero, 76($c3)
; PURECAP-NEXT:    csw $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 78, i1 false)
  ret void
}

define void @zero79(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero79:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    csb $zero, $zero, 78($c3)
; PURECAP-NEXT:    csh $zero, $zero, 76($c3)
; PURECAP-NEXT:    csw $zero, $zero, 72($c3)
; PURECAP-NEXT:    csd $zero, $zero, 64($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 48($c3)
; PURECAP-NEXT:    csc $cnull, $zero, 32($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csc $cnull, $zero, 16($c3)
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 79, i1 false)
  ret void
}

declare void @llvm.memset.p200.i64(ptr addrspace(200) nocapture writeonly, i8, i64, i1 immarg) #0

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: write) }
