; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/captable-global-func-ptrtoint-in-csetoffset.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP
; Check that we don't accidentally create a nonsense COPY node ($at_64 = COPY killed renamable $c1)
; when the result of the GlobalAddr goes through a ptrtoint

declare i32 @foo(ptr addrspace(200)) addrspace(200)

declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200), i64) addrspace(200)

define void @main(ptr addrspace(200) %arg) addrspace(200) nounwind {
; PURECAP-LABEL: main:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset $c11, $c11, -16
; PURECAP-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    clcbi $c1, %captab20(foo)($c1)
; PURECAP-NEXT:    cgetaddr $1, $c1
; PURECAP-NEXT:    csetoffset $c12, $c3, $1
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    nop
; PURECAP-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 16
entry:
  %0 = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) %arg, i64 ptrtoint (ptr addrspace(200) @foo to i64))
  %call3 = call i32 %0(ptr addrspace(200) undef)
  ret void
}
