; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-store.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap %s -o - | FileCheck %s --check-prefix=PURECAP

define void @storeToPtr1(ptr addrspace(200) nocapture %a, i8 signext %v) nounwind {
; HYBRID-LABEL: storeToPtr1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csb $4, $zero, 0($c3)
;
; PURECAP-LABEL: storeToPtr1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csb $4, $zero, 0($c3)
entry:
  store i8 %v, ptr addrspace(200) %a, align 1
  ret void
}

define void @storeToPtr2(ptr addrspace(200) nocapture %a, i16 signext %v) nounwind {
; HYBRID-LABEL: storeToPtr2:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csh $4, $zero, 0($c3)
;
; PURECAP-LABEL: storeToPtr2:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csh $4, $zero, 0($c3)
entry:
  store i16 %v, ptr addrspace(200) %a, align 2
  ret void
}

define void @storeToPtr4(ptr addrspace(200) nocapture %a, i32 %v) nounwind {
; HYBRID-LABEL: storeToPtr4:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csw $4, $zero, 0($c3)
;
; PURECAP-LABEL: storeToPtr4:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csw $4, $zero, 0($c3)
entry:
  store i32 %v, ptr addrspace(200) %a, align 4
  ret void
}

define void @storeToPtr8(ptr addrspace(200) nocapture %a, i64 %v) nounwind {
; HYBRID-LABEL: storeToPtr8:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csd $4, $zero, 0($c3)
;
; PURECAP-LABEL: storeToPtr8:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csd $4, $zero, 0($c3)
entry:
  store i64 %v, ptr addrspace(200) %a, align 8
  ret void
}
