; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-purecap-vaargs.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -O1 %s -o - | FileCheck %s --check-prefix=PURECAP

@va_copy = common addrspace(200) global ptr addrspace(200) null, align 16

define void @copy_to_global(ptr addrspace(200) nocapture readnone %y, i32 signext %x, ...) addrspace(200) nounwind {
; PURECAP-LABEL: copy_to_global:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset $c11, $c11, -16
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    csetbounds $c2, $c11, 16
; PURECAP-NEXT:    csc $c13, $zero, 0($c2)
; PURECAP-NEXT:    clc $c2, $zero, 0($c2)
; PURECAP-NEXT:    clcbi $c1, %captab20(va_copy)($c1)
; PURECAP-NEXT:    csc $c2, $zero, 0($c1)
; PURECAP-NEXT:    cgetnull $c13
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 16
  %1 = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.va_start.p200(ptr addrspace(200) %1)
  call void @llvm.va_copy.p200.p200(ptr addrspace(200) @va_copy, ptr addrspace(200) %1)
  call void @llvm.va_end.p200(ptr addrspace(200) %1)
  ret void
}

define ptr addrspace(200) @copy_from_global() addrspace(200) nounwind {
; PURECAP-LABEL: copy_from_global:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset $c11, $c11, -16
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    clcbi $c1, %captab20(va_copy)($c1)
; PURECAP-NEXT:    clc $c1, $zero, 0($c1)
; PURECAP-NEXT:    csetbounds $c2, $c11, 16
; PURECAP-NEXT:    csc $c1, $zero, 0($c2)
; PURECAP-NEXT:    clc $c3, $zero, 0($c11)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 16
  %1 = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.va_copy.p200.p200(ptr addrspace(200) %1, ptr addrspace(200) @va_copy)
  %2 = load ptr addrspace(200), ptr addrspace(200) %1, align 16
  ret ptr addrspace(200) %2
}

declare void @llvm.va_start.p200(ptr addrspace(200)) addrspace(200)
declare void @llvm.va_copy.p200.p200(ptr addrspace(200), ptr addrspace(200)) addrspace(200)
declare void @llvm.va_end.p200(ptr addrspace(200)) addrspace(200)
