; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-byval-argument-varargs.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP
; we should really be getting an error when compiling this with the hybrid ABI (alloca in AS 200)
; RUNTODO: not llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 < %s 2>&1 | FileCheck %s -check-prefix BAD-ABI
; BAD-ABI: error: abc

%struct.Dwarf_Error = type { [1024 x i32] }

@a = common local_unnamed_addr addrspace(200) global %struct.Dwarf_Error zeroinitializer, align 4

; Function Attrs: nounwind
define i32 @fn1() local_unnamed_addr #0 {
; PURECAP-LABEL: fn1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    daddiu $1, $zero, -8272
; PURECAP-NEXT:    cincoffset $c11, $c11, $1
; PURECAP-NEXT:    daddiu $1, $zero, 8264
; PURECAP-NEXT:    csd $16, $1, 0($c11) # 8-byte Folded Spill
; PURECAP-NEXT:    csc $c19, $zero, 8240($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    csc $c18, $zero, 8224($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    csc $c17, $zero, 8208($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c19, $1
; PURECAP-NEXT:    daddiu $16, $zero, 4096
; PURECAP-NEXT:    clcbi $c4, %captab20(a)($c19)
; PURECAP-NEXT:    clcbi $c12, %capcall20(memcpy)($c19)
; PURECAP-NEXT:    daddiu $1, $zero, 4112
; PURECAP-NEXT:    cincoffset $c3, $c11, $1
; PURECAP-NEXT:    csetbounds $c3, $c3, $16
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    daddiu $4, $zero, 4096
; PURECAP-NEXT:    clcbi $c12, %capcall20(memcpy)($c19)
; PURECAP-NEXT:    daddiu $1, $zero, 4112
; PURECAP-NEXT:    cincoffset $c4, $c11, $1
; PURECAP-NEXT:    csetbounds $c4, $c4, $16
; PURECAP-NEXT:    daddiu $4, $zero, 4096
; PURECAP-NEXT:    cmove $c18, $c11
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    cmove $c3, $c18
; PURECAP-NEXT:    csetbounds $c1, $c18, $16
; PURECAP-NEXT:    clcbi $c12, %capcall20(fn2)($c19)
; PURECAP-NEXT:    ori $1, $zero, 65495
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    candperm $c13, $c1, $1
; PURECAP-NEXT:    clc $c17, $zero, 8208($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    clc $c18, $zero, 8224($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    clc $c19, $zero, 8240($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    daddiu $1, $zero, 8264
; PURECAP-NEXT:    cld $16, $1, 0($c11) # 8-byte Folded Reload
; PURECAP-NEXT:    daddiu $1, $zero, 8272
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, $1
entry:
  %tmp = alloca %struct.Dwarf_Error, align 8, addrspace(200)
  %0 = bitcast ptr addrspace(200) %tmp to ptr addrspace(200)
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) nonnull align 4 %0, ptr addrspace(200) align 4 @a, i64 4096, i1 false)
  %call = call i32 (...) @fn2(ptr addrspace(200) nonnull byval(%struct.Dwarf_Error) align 8 %tmp) #0
  ret i32 undef
}

; Function Attrs: nounwind
declare i32 @fn2(...) #0

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg) #1

attributes #0 = { nounwind }
attributes #1 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
