; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-float.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap %s -o - | FileCheck %s --check-prefix=PURECAP

; Function Attrs: nounwind memory(read)
define double @load64(ptr addrspace(200) nocapture readonly %x) #0 {
; HYBRID-LABEL: load64:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cld $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    dmtc1 $1, $f0
;
; PURECAP-LABEL: load64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cld $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    dmtc1 $1, $f0
entry:
  %0 = load double, ptr addrspace(200) %x, align 8
  ret double %0
}

; Function Attrs: nounwind memory(read)
define float @load32(ptr addrspace(200) nocapture readonly %x) #0 {
; HYBRID-LABEL: load32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clw $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    mtc1 $1, $f0
;
; PURECAP-LABEL: load32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    mtc1 $1, $f0
entry:
  %0 = load float, ptr addrspace(200) %x, align 4
  ret float %0
}

; Function Attrs: nounwind
define void @store64(ptr addrspace(200) nocapture %x, double %y) #1 {
; HYBRID-LABEL: store64:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    dmfc1 $1, $f12
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csd $1, $zero, 0($c3)
;
; PURECAP-LABEL: store64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    dmfc1 $1, $f12
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csd $1, $zero, 0($c3)
entry:
  store double %y, ptr addrspace(200) %x, align 8
  ret void
}

; Function Attrs: nounwind
define void @store32(ptr addrspace(200) nocapture %x, float %y) #1 {
; HYBRID-LABEL: store32:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    mfc1 $1, $f12
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csw $1, $zero, 0($c3)
;
; PURECAP-LABEL: store32:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    mfc1 $1, $f12
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    csw $1, $zero, 0($c3)
entry:
  store float %y, ptr addrspace(200) %x, align 4
  ret void
}

attributes #0 = { nounwind }
attributes #1 = { nounwind "use-soft-float"="false" }
