; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-member-pointer.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -asm-verbose -verify-regalloc -O0 %s -o - | FileCheck %s
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -asm-verbose -verify-regalloc -O1 %s -o - | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -asm-verbose -verify-regalloc -O2 %s -o - | FileCheck %s --check-prefix=OPT

@global_func_ptr = external local_unnamed_addr addrspace(200) global ptr addrspace(200), align 32

; Function Attrs: nounwind
define i32 @func_ptr_dereference(ptr addrspace(200) %a, ptr addrspace(200) inreg %ptr.coerce0, i64 inreg %ptr.coerce1) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: func_ptr_dereference:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset $c11, $c11, -80
; CHECK-NEXT:    csc $c17, $zero, 64($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c4, $zero, 16($c11) # 16-byte Folded Spill
; CHECK-NEXT:    dsra $1, $4, 1
; CHECK-NEXT:    cincoffset $c1, $c3, $1
; CHECK-NEXT:    csc $c1, $zero, 32($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c1, $zero, 48($c11) # 16-byte Folded Spill
; CHECK-NEXT:    andi $1, $4, 1
; CHECK-NEXT:    beqz $1, .LBB0_3
; CHECK-NEXT:    nop
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    b .LBB0_2
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_2: # %memptr.virtual
; CHECK-NEXT:    clc $c2, $zero, 16($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c1, $zero, 48($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c1, $zero, 0($c1)
; CHECK-NEXT:    cgetaddr $1, $c2
; CHECK-NEXT:    clc $c1, $1, 0($c1)
; CHECK-NEXT:    csc $c1, $zero, 0($c11) # 16-byte Folded Spill
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_3: # %memptr.nonvirtual
; CHECK-NEXT:    clc $c1, $zero, 16($c11) # 16-byte Folded Reload
; CHECK-NEXT:    csc $c1, $zero, 0($c11) # 16-byte Folded Spill
; CHECK-NEXT:    b .LBB0_4
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB0_4: # %memptr.end
; CHECK-NEXT:    clc $c3, $zero, 32($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c12, $zero, 0($c11) # 16-byte Folded Reload
; CHECK-NEXT:    cjalr $c12, $c17
; CHECK-NEXT:    nop
; CHECK-NEXT:    clc $c17, $zero, 64($c11) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset $c11, $c11, 80
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    nop
;
; OPT-LABEL: func_ptr_dereference:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    dsra $1, $4, 1
; OPT-NEXT:    andi $2, $4, 1
; OPT-NEXT:    beqz $2, .LBB0_2
; OPT-NEXT:    cincoffset $c3, $c3, $1
; OPT-NEXT:  # %bb.1: # %memptr.virtual
; OPT-NEXT:    clc $c1, $zero, 0($c3)
; OPT-NEXT:    cgetaddr $1, $c4
; OPT-NEXT:    clc $c4, $1, 0($c1)
; OPT-NEXT:  .LBB0_2: # %memptr.end
; OPT-NEXT:    cincoffset $c11, $c11, -16
; OPT-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; OPT-NEXT:    cmove $c12, $c4
; OPT-NEXT:    cjalr $c12, $c17
; OPT-NEXT:    nop
; OPT-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; OPT-NEXT:    cjr $c17
; OPT-NEXT:    cincoffset $c11, $c11, 16
entry:
  %memptr.adj.shifted = ashr i64 %ptr.coerce1, 1
  %this.not.adjusted = bitcast ptr addrspace(200) %a to ptr addrspace(200)
  %memptr.vtable.addr = getelementptr inbounds i8, ptr addrspace(200) %this.not.adjusted, i64 %memptr.adj.shifted
  %this.adjusted = bitcast ptr addrspace(200) %memptr.vtable.addr to ptr addrspace(200)
  %0 = and i64 %ptr.coerce1, 1
  %memptr.isvirtual = icmp eq i64 %0, 0
  br i1 %memptr.isvirtual, label %memptr.nonvirtual, label %memptr.virtual

memptr.virtual:                                   ; preds = %entry
  %1 = bitcast ptr addrspace(200) %memptr.vtable.addr to ptr addrspace(200)
  %vtable = load ptr addrspace(200), ptr addrspace(200) %1, align 32, !tbaa !2
  %memptr.vtable.offset = ptrtoint ptr addrspace(200) %ptr.coerce0 to i64
  %2 = getelementptr i8, ptr addrspace(200) %vtable, i64 %memptr.vtable.offset
  %3 = bitcast ptr addrspace(200) %2 to ptr addrspace(200)
  %memptr.virtualfn = load ptr addrspace(200), ptr addrspace(200) %3, align 32
  br label %memptr.end

memptr.nonvirtual:                                ; preds = %entry
  %memptr.nonvirtualfn = bitcast ptr addrspace(200) %ptr.coerce0 to ptr addrspace(200)
  br label %memptr.end

memptr.end:                                       ; preds = %memptr.nonvirtual, %memptr.virtual
  %4 = phi ptr addrspace(200) [ %memptr.virtualfn, %memptr.virtual ], [ %memptr.nonvirtualfn, %memptr.nonvirtual ]
  %call = tail call i32 %4(ptr addrspace(200) %this.adjusted) #0
  ret i32 %call
}

attributes #0 = { nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"PIC Level", i32 2}
!2 = !{!3, !3, i64 0}
!3 = !{!"vtable pointer", !4, i64 0}
!4 = !{!"Simple C++ TBAA"}
