; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-byval-argument-hybrid.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=HYBRID
%struct.arg_1000_long = type { [1000 x i64] }
%struct.arg_1000___intcap_t = type { [1000 x ptr addrspace(200)] }

@global_1000_long_struct = common global %struct.arg_1000_long zeroinitializer, align 8
@global_1000___intcap_t_struct = common global %struct.arg_1000___intcap_t zeroinitializer, align 16

; Function Attrs: nounwind
define void @call_1000_long_byval() local_unnamed_addr #0 {
; HYBRID-LABEL: call_1000_long_byval:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $sp, $sp, -7968
; HYBRID-NEXT:    sd $ra, 7960($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $gp, 7952($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $16, 7944($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lui $1, %hi(%neg(%gp_rel(call_1000_long_byval)))
; HYBRID-NEXT:    daddu $1, $1, $25
; HYBRID-NEXT:    daddiu $gp, $1, %lo(%neg(%gp_rel(call_1000_long_byval)))
; HYBRID-NEXT:    ld $16, %got_disp(global_1000_long_struct)($gp)
; HYBRID-NEXT:    ld $25, %call16(memcpy)($gp)
; HYBRID-NEXT:    daddiu $5, $16, 64
; HYBRID-NEXT:    daddiu $6, $zero, 7936
; HYBRID-NEXT:    .reloc .Ltmp0, R_MIPS_JALR, memcpy
; HYBRID-NEXT:  .Ltmp0:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    move $4, $sp
; HYBRID-NEXT:    ld $11, 56($16)
; HYBRID-NEXT:    ld $10, 48($16)
; HYBRID-NEXT:    ld $9, 40($16)
; HYBRID-NEXT:    ld $8, 32($16)
; HYBRID-NEXT:    ld $7, 24($16)
; HYBRID-NEXT:    ld $6, 16($16)
; HYBRID-NEXT:    ld $5, 8($16)
; HYBRID-NEXT:    ld $4, 0($16)
; HYBRID-NEXT:    ld $25, %call16(take_1000_long_byval)($gp)
; HYBRID-NEXT:    .reloc .Ltmp1, R_MIPS_JALR, take_1000_long_byval
; HYBRID-NEXT:  .Ltmp1:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    nop
; HYBRID-NEXT:    ld $16, 7944($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $gp, 7952($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $ra, 7960($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $sp, $sp, 7968
entry:
  tail call void @take_1000_long_byval(ptr nonnull byval(%struct.arg_1000_long) align 8 @global_1000_long_struct) #0
  ret void
}

declare void @other_func(ptr) local_unnamed_addr #0

declare void @take_1000_long_byval(ptr byval(%struct.arg_1000_long) align 8) local_unnamed_addr #0

; Function Attrs: nounwind
define void @call_1000___intcap_t_byval() local_unnamed_addr #0 {
; HYBRID-LABEL: call_1000___intcap_t_byval:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $sp, $sp, -15968
; HYBRID-NEXT:    sd $ra, 15960($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $gp, 15952($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    sd $16, 15944($sp) # 8-byte Folded Spill
; HYBRID-NEXT:    lui $1, %hi(%neg(%gp_rel(call_1000___intcap_t_byval)))
; HYBRID-NEXT:    daddu $1, $1, $25
; HYBRID-NEXT:    daddiu $gp, $1, %lo(%neg(%gp_rel(call_1000___intcap_t_byval)))
; HYBRID-NEXT:    ld $16, %got_disp(global_1000___intcap_t_struct)($gp)
; HYBRID-NEXT:    ld $25, %call16(memcpy)($gp)
; HYBRID-NEXT:    daddiu $5, $16, 64
; HYBRID-NEXT:    daddiu $6, $zero, 15936
; HYBRID-NEXT:    .reloc .Ltmp2, R_MIPS_JALR, memcpy
; HYBRID-NEXT:  .Ltmp2:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    move $4, $sp
; HYBRID-NEXT:    ld $11, 56($16)
; HYBRID-NEXT:    ld $10, 48($16)
; HYBRID-NEXT:    ld $9, 40($16)
; HYBRID-NEXT:    ld $8, 32($16)
; HYBRID-NEXT:    ld $7, 24($16)
; HYBRID-NEXT:    ld $6, 16($16)
; HYBRID-NEXT:    ld $5, 8($16)
; HYBRID-NEXT:    ld $4, 0($16)
; HYBRID-NEXT:    ld $25, %call16(take_1000___intcap_t_byval)($gp)
; HYBRID-NEXT:    .reloc .Ltmp3, R_MIPS_JALR, take_1000___intcap_t_byval
; HYBRID-NEXT:  .Ltmp3:
; HYBRID-NEXT:    jalr $25
; HYBRID-NEXT:    nop
; HYBRID-NEXT:    ld $16, 15944($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $gp, 15952($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    ld $ra, 15960($sp) # 8-byte Folded Reload
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $sp, $sp, 15968
entry:
  tail call void @take_1000___intcap_t_byval(ptr nonnull byval(%struct.arg_1000___intcap_t) align 16 @global_1000___intcap_t_struct) #0
  ret void
}

declare void @take_1000___intcap_t_byval(ptr byval(%struct.arg_1000___intcap_t) align 16) local_unnamed_addr #0

attributes #0 = { nounwind }
