; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-stack-variable.ll
;; Check the cap-typed @llvm.stacksave.p200 / @llvm.stackrestore.p200
;; intrinsics around a VLA inside a loop, ensuring the saved cap stack
;; pointer is restored each iteration so the stack does not grow without
;; bound.
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -O1 %s -o - | FileCheck %s --check-prefix=CHECK

define void @dynamic_alloca(i32 signext %x) local_unnamed_addr nounwind {
; CHECK-LABEL: dynamic_alloca:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset $c11, $c11, -96
; CHECK-NEXT:    csd $18, $zero, 88($c11) # 8-byte Folded Spill
; CHECK-NEXT:    csd $17, $zero, 80($c11) # 8-byte Folded Spill
; CHECK-NEXT:    csd $16, $zero, 72($c11) # 8-byte Folded Spill
; CHECK-NEXT:    csc $c24, $zero, 48($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c19, $zero, 32($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c18, $zero, 16($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset $c24, $c11, $zero
; CHECK-NEXT:    move $16, $4
; CHECK-NEXT:    blez $16, .LBB0_3
; CHECK-NEXT:    nop
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; CHECK-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; CHECK-NEXT:    cgetpccincoffset $c18, $1
; CHECK-NEXT:    dsll $1, $16, 32
; CHECK-NEXT:    dsrl $1, $1, 32
; CHECK-NEXT:    dsll $17, $1, 2
; CHECK-NEXT:    daddiu $1, $17, 15
; CHECK-NEXT:    daddiu $2, $zero, 1
; CHECK-NEXT:    dsll $2, $2, 35
; CHECK-NEXT:    daddiu $2, $2, -16
; CHECK-NEXT:    and $18, $1, $2
; CHECK-NEXT:  .LBB0_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmove $c19, $c11
; CHECK-NEXT:    croundrepresentablelength $1, $18
; CHECK-NEXT:    cgetaddr $2, $c11
; CHECK-NEXT:    dsubu $2, $2, $1
; CHECK-NEXT:    crepresentablealignmentmask $3, $18
; CHECK-NEXT:    and $2, $2, $3
; CHECK-NEXT:    csetaddr $c1, $c11, $2
; CHECK-NEXT:    csetbounds $c2, $c1, $1
; CHECK-NEXT:    cmove $c11, $c1
; CHECK-NEXT:    clcbi $c12, %capcall20(use_arg)($c18)
; CHECK-NEXT:    cjalr $c12, $c17
; CHECK-NEXT:    csetbounds $c3, $c2, $17
; CHECK-NEXT:    addiu $16, $16, -1
; CHECK-NEXT:    bnez $16, .LBB0_2
; CHECK-NEXT:    cmove $c11, $c19
; CHECK-NEXT:  .LBB0_3: # %for.cond.cleanup
; CHECK-NEXT:    cincoffset $c11, $c24, $zero
; CHECK-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c18, $zero, 16($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c19, $zero, 32($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c24, $zero, 48($c11) # 16-byte Folded Reload
; CHECK-NEXT:    cld $16, $zero, 72($c11) # 8-byte Folded Reload
; CHECK-NEXT:    cld $17, $zero, 80($c11) # 8-byte Folded Reload
; CHECK-NEXT:    cld $18, $zero, 88($c11) # 8-byte Folded Reload
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c11, $c11, 96
entry:
  %cmp4 = icmp sgt i32 %x, 0
  br i1 %cmp4, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %0 = zext i32 %x to i64
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.05 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %1 = call ptr addrspace(200) @llvm.stacksave.p200()
  %vla = alloca i32, i64 %0, align 4, addrspace(200)
  call void @use_arg(ptr addrspace(200) nonnull %vla)
  call void @llvm.stackrestore.p200(ptr addrspace(200) %1)
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond = icmp eq i32 %inc, %x
  br i1 %exitcond, label %for.cond.cleanup, label %for.body
}

; Function Attrs: nounwind
declare void @use_arg(ptr addrspace(200)) nounwind

declare ptr addrspace(200) @llvm.stacksave.p200()

declare void @llvm.stackrestore.p200(ptr addrspace(200))
