; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-bitfield.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap %s -o - | FileCheck %s --check-prefix=PURECAP
; Test that we can correctly legalise i128 and generate pointer arithmetic that
; doesn't crash the compiler.

%struct.foo = type { i128 }

@x = internal addrspace(200) global %struct.foo zeroinitializer, align 8

; Function Attrs: noinline nounwind
define i32 @main(i32 signext %argc, ptr addrspace(200) %argv) #0 {
; PURECAP-LABEL: main:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset $c11, $c11, -64
; PURECAP-NEXT:    csc $c24, $zero, 48($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    csc $c17, $zero, 32($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    cincoffset $c24, $c11, $zero
; PURECAP-NEXT:    cgetaddr $1, $c11
; PURECAP-NEXT:    daddiu $2, $zero, -32
; PURECAP-NEXT:    and $1, $1, $2
; PURECAP-NEXT:    csetaddr $c11, $c11, $1
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    csw $zero, $zero, 28($c11)
; PURECAP-NEXT:    clcbi $c1, %captab20(x)($c1)
; PURECAP-NEXT:    csw $4, $zero, 24($c11)
; PURECAP-NEXT:    csc $c3, $zero, 0($c11)
; PURECAP-NEXT:    cld $1, $zero, 8($c1)
; PURECAP-NEXT:    lui $2, 65535
; PURECAP-NEXT:    ori $2, $2, 65535
; PURECAP-NEXT:    dsll $2, $2, 32
; PURECAP-NEXT:    daddiu $2, $2, 1
; PURECAP-NEXT:    and $1, $1, $2
; PURECAP-NEXT:    ori $1, $1, 2
; PURECAP-NEXT:    addiu $2, $zero, 0
; PURECAP-NEXT:    csd $1, $zero, 8($c1)
; PURECAP-NEXT:    cincoffset $c11, $c24, $zero
; PURECAP-NEXT:    clc $c17, $zero, 32($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    clc $c24, $zero, 48($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 64
entry:
  %retval = alloca i32, align 4, addrspace(200)
  %argc.addr = alloca i32, align 4, addrspace(200)
  %argv.addr = alloca ptr addrspace(200), align 32, addrspace(200)
  store i32 0, ptr addrspace(200) %retval, align 4
  store i32 %argc, ptr addrspace(200) %argc.addr, align 4
  store ptr addrspace(200) %argv, ptr addrspace(200) %argv.addr, align 32
  %bf.load = load i128, ptr addrspace(200) @x, align 4
  %bf.clear = and i128 %bf.load, -4294967295
  %bf.set = or i128 %bf.clear, 2
  store i128 %bf.set, ptr addrspace(200) @x, align 4
  ret i32 0
}

attributes #0 = { noinline nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 8, !"PIC Level", i32 2}
