; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cincoffset-immediate.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP

define ptr addrspace(200) @imm(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: imm:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c3, $c3, 1023
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1023
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @imm1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: imm1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c3, $c3, -1024
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1024
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: reg:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    daddiu $1, $zero, 1024
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c3, $c3, $1
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1024
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; PURECAP-LABEL: reg1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    daddiu $1, $zero, -1025
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c3, $c3, $1
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1025
  ret ptr addrspace(200) %add.ptr
}
