; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-csetbounds-immediate.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=HYBRID

declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200), i64)

define ptr addrspace(200) @setBoundsUnknown(ptr addrspace(200) %c, i64 %bounds) nounwind {
; HYBRID-LABEL: setBoundsUnknown:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csetbounds $c3, $c3, $4
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 %bounds)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstant1(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstant1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csetbounds $c3, $c3, 1
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 1)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstantMaxImmediate(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantMaxImmediate:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csetbounds $c3, $c3, 2047
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 2047)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstantTooBigForImm(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantTooBigForImm:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $1, $zero, 2048
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csetbounds $c3, $c3, $1
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 2048)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsNegative(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsNegative:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    daddiu $1, $zero, -2
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csetbounds $c3, $c3, $1
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 -2)
  ret ptr addrspace(200) %0
}
