; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-load.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap %s -o - | FileCheck %s --check-prefix=PURECAP

define zeroext i8 @loadFromPtr1U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr1U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clb $1, $zero, 0($c3)
; HYBRID-NEXT:    addiu $1, $1, 12
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    andi $2, $1, 255
;
; PURECAP-LABEL: loadFromPtr1U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clb $1, $zero, 0($c3)
; PURECAP-NEXT:    addiu $1, $1, 12
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    andi $2, $1, 255
entry:
  %0 = load i8, ptr addrspace(200) %a, align 1
  %conv = zext i8 %0 to i32
  %add = add nsw i32 %conv, 12
  %conv1 = trunc i32 %add to i8
  ret i8 %conv1
}

define signext i8 @loadFromPtr1(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clb $1, $zero, 0($c3)
; HYBRID-NEXT:    sll $1, $1, 24
; HYBRID-NEXT:    lui $2, 3072
; HYBRID-NEXT:    addu $1, $1, $2
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    sra $2, $1, 24
;
; PURECAP-LABEL: loadFromPtr1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clb $1, $zero, 0($c3)
; PURECAP-NEXT:    sll $1, $1, 24
; PURECAP-NEXT:    lui $2, 3072
; PURECAP-NEXT:    addu $1, $1, $2
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    sra $2, $1, 24
entry:
  %0 = load i8, ptr addrspace(200) %a, align 1
  %conv2 = zext i8 %0 to i32
  %add = add nsw i32 %conv2, 12
  %conv1 = trunc i32 %add to i8
  ret i8 %conv1
}

define zeroext i16 @loadFromPtr2U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr2U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clh $1, $zero, 0($c3)
; HYBRID-NEXT:    addiu $1, $1, 12
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    andi $2, $1, 65535
;
; PURECAP-LABEL: loadFromPtr2U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clh $1, $zero, 0($c3)
; PURECAP-NEXT:    addiu $1, $1, 12
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    andi $2, $1, 65535
entry:
  %0 = load i16, ptr addrspace(200) %a, align 2
  %conv = zext i16 %0 to i32
  %add = add nsw i32 %conv, 12
  %conv1 = trunc i32 %add to i16
  ret i16 %conv1
}

define signext i16 @loadFromPtr2(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr2:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clh $1, $zero, 0($c3)
; HYBRID-NEXT:    sll $1, $1, 16
; HYBRID-NEXT:    lui $2, 12
; HYBRID-NEXT:    addu $1, $1, $2
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    sra $2, $1, 16
;
; PURECAP-LABEL: loadFromPtr2:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clh $1, $zero, 0($c3)
; PURECAP-NEXT:    sll $1, $1, 16
; PURECAP-NEXT:    lui $2, 12
; PURECAP-NEXT:    addu $1, $1, $2
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    sra $2, $1, 16
entry:
  %0 = load i16, ptr addrspace(200) %a, align 2
  %conv2 = zext i16 %0 to i32
  %add = add nsw i32 %conv2, 12
  %conv1 = trunc i32 %add to i16
  ret i16 %conv1
}

define i32 @loadFromPtr4U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr4U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clw $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    addiu $2, $1, 12
;
; PURECAP-LABEL: loadFromPtr4U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    addiu $2, $1, 12
entry:
  %0 = load i32, ptr addrspace(200) %a, align 4
  %add = add i32 %0, 12
  ret i32 %add
}

define i32 @loadFromPtr4(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr4:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    clw $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    addiu $2, $1, 12
;
; PURECAP-LABEL: loadFromPtr4:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    addiu $2, $1, 12
entry:
  %0 = load i32, ptr addrspace(200) %a, align 4
  %add = add nsw i32 %0, 12
  ret i32 %add
}

define i64 @loadFromPtr8U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr8U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cld $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $2, $1, 12
;
; PURECAP-LABEL: loadFromPtr8U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cld $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    daddiu $2, $1, 12
entry:
  %0 = load i64, ptr addrspace(200) %a, align 8
  %add = add i64 %0, 12
  ret i64 %add
}

define i64 @loadFromPtr8(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr8:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cld $1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $2, $1, 12
;
; PURECAP-LABEL: loadFromPtr8:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cld $1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    daddiu $2, $1, 12
entry:
  %0 = load i64, ptr addrspace(200) %a, align 8
  %add = add nsw i64 %0, 12
  ret i64 %add
}
