; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-store-cap.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 %s -o - | FileCheck %s --check-prefix=HYBRID

@n = common global ptr addrspace(200) null, align 32

define void @set(ptr addrspace(200) %h) nounwind {
; HYBRID-LABEL: set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    lui $1, %hi(%neg(%gp_rel(set)))
; HYBRID-NEXT:    daddu $1, $1, $25
; HYBRID-NEXT:    daddiu $1, $1, %lo(%neg(%gp_rel(set)))
; HYBRID-NEXT:    ld $1, %got_disp(n)($1)
; HYBRID-NEXT:    clc $c1, $1, 0($ddc)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    csc $c3, $zero, 0($c1)
  %1 = load ptr addrspace(200), ptr @n, align 32
  store ptr addrspace(200) %h, ptr addrspace(200) %1, align 32
  ret void
}
