; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/inline-asm-clobber.ll
; CHERI-GENERIC-UTC: mir
; CHERI-GENERIC-UTC: llc
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs -o - -O0 %s -stop-after=instruction-select | FileCheck %s -check-prefix MIR
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs -o - -O3 %s | FileCheck %s -enable-var-scope
;
; https://github.com/CTSRD-CHERI/llvm/issues/274
;
; Source code:
; int test(int intval, const char* ptrval) {
;   __asm__ ("syscall\n"
;   :
;   :
;   : "a0", "$c3");
;   char x = *((volatile char*)ptrval);
;   return (int)x + intval;
; }
;
; The capability clobber registers were previously off by one: -> $c3 would save $c4, etc.

define i32 @test_clobber_c2(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $2, $4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .set push
; CHECK-NEXT:    .set at
; CHECK-NEXT:    .set macro
; CHECK-NEXT:    .set reorder
; CHECK-EMPTY:
; CHECK-NEXT:    syscall
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:    .set pop
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb $1, $zero, 0($c3)
; CHECK-NEXT:    clb $3, $zero, 0($c4)
; CHECK-NEXT:    addu $1, $1, $2
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    addu $2, $3, $1
; MIR-LABEL: name: test_clobber_c2
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $a0_64, $c3, $c4
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $v1 = OR $a0, $zero, implicit killed $a0_64
; MIR-NEXT:   INLINEASM &"syscall\0A", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $a0, 12 /* clobber */, implicit-def dead early-clobber $c2, 12 /* clobber */, implicit-def dead early-clobber $at
; MIR-NEXT:   renamable $v0 = CAPLOAD832 $zero_64, 0, killed renamable $c3 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $at = CAPLOAD832 $zero_64, 0, killed renamable $c4 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $v0, killed renamable $v1
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $at, killed renamable $v0
; MIR-NEXT:   PseudoReturnCap $c17 {
; MIR-NEXT:     $zero = SLL $zero, 0
; MIR-NEXT:   }
entry:
  tail call void asm sideeffect "syscall\0A", "~{$4},~{$c2},~{$1}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c3(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove $c1, $c3
; CHECK-NEXT:    move $2, $4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .set push
; CHECK-NEXT:    .set at
; CHECK-NEXT:    .set macro
; CHECK-NEXT:    .set reorder
; CHECK-EMPTY:
; CHECK-NEXT:    syscall
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:    .set pop
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb $1, $zero, 0($c1)
; CHECK-NEXT:    clb $3, $zero, 0($c4)
; CHECK-NEXT:    addu $1, $1, $2
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    addu $2, $3, $1
; MIR-LABEL: name: test_clobber_c3
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $a0_64, $c3, $c4
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, -16
; MIR-NEXT:   CFI_INSTRUCTION def_cfa_offset 16
; MIR-NEXT:   STORECAP $c3, $zero_64, 0, $c11 :: (store (s128) into %stack.0)
; MIR-NEXT:   $v1 = OR $a0, $zero, implicit killed $a0_64
; MIR-NEXT:   INLINEASM &"syscall\0A", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $a0, 12 /* clobber */, implicit-def early-clobber $c3, 12 /* clobber */, implicit-def dead early-clobber $at
; MIR-NEXT:   $c3 = LOADCAP $zero_64, 0, $c11 :: (load (s128) from %stack.0)
; MIR-NEXT:   renamable $v0 = CAPLOAD832 $zero_64, 0, killed renamable $c3 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $at = CAPLOAD832 $zero_64, 0, killed renamable $c4 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $v0, killed renamable $v1
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $at, killed renamable $v0
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, 16
; MIR-NEXT:   PseudoReturnCap $c17 {
; MIR-NEXT:     $zero = SLL $zero, 0
; MIR-NEXT:   }
entry:
  tail call void asm sideeffect "syscall\0A", "~{$4},~{$c3},~{$1}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c4(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove $c1, $c4
; CHECK-NEXT:    move $2, $4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .set push
; CHECK-NEXT:    .set at
; CHECK-NEXT:    .set macro
; CHECK-NEXT:    .set reorder
; CHECK-EMPTY:
; CHECK-NEXT:    syscall
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:    .set pop
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb $1, $zero, 0($c3)
; CHECK-NEXT:    clb $3, $zero, 0($c1)
; CHECK-NEXT:    addu $1, $1, $2
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    addu $2, $3, $1
; MIR-LABEL: name: test_clobber_c4
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $a0_64, $c3, $c4
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, -16
; MIR-NEXT:   CFI_INSTRUCTION def_cfa_offset 16
; MIR-NEXT:   STORECAP $c4, $zero_64, 0, $c11 :: (store (s128) into %stack.0)
; MIR-NEXT:   $v1 = OR $a0, $zero, implicit killed $a0_64
; MIR-NEXT:   INLINEASM &"syscall\0A", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $a0, 12 /* clobber */, implicit-def early-clobber $c4, 12 /* clobber */, implicit-def dead early-clobber $at
; MIR-NEXT:   $c4 = LOADCAP $zero_64, 0, $c11 :: (load (s128) from %stack.0)
; MIR-NEXT:   renamable $v0 = CAPLOAD832 $zero_64, 0, killed renamable $c3 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $at = CAPLOAD832 $zero_64, 0, killed renamable $c4 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $v0, killed renamable $v1
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $at, killed renamable $v0
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, 16
; MIR-NEXT:   PseudoReturnCap $c17 {
; MIR-NEXT:     $zero = SLL $zero, 0
; MIR-NEXT:   }
entry:
  tail call void asm sideeffect "syscall\0A", "~{$4},~{$c4},~{$1}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c3_c4(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c3_c4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove $c1, $c4
; CHECK-NEXT:    cmove $c2, $c3
; CHECK-NEXT:    move $2, $4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    .set push
; CHECK-NEXT:    .set at
; CHECK-NEXT:    .set macro
; CHECK-NEXT:    .set reorder
; CHECK-EMPTY:
; CHECK-NEXT:    syscall
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:    .set pop
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb $1, $zero, 0($c2)
; CHECK-NEXT:    clb $3, $zero, 0($c1)
; CHECK-NEXT:    addu $1, $1, $2
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    addu $2, $3, $1
; MIR-LABEL: name: test_clobber_c3_c4
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $a0_64, $c3, $c4
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, -32
; MIR-NEXT:   CFI_INSTRUCTION def_cfa_offset 32
; MIR-NEXT:   STORECAP $c4, $zero_64, 0, $c11 :: (store (s128) into %stack.1)
; MIR-NEXT:   STORECAP $c3, $zero_64, 16, $c11 :: (store (s128) into %stack.0)
; MIR-NEXT:   $v1 = OR $a0, $zero, implicit killed $a0_64
; MIR-NEXT:   INLINEASM &"syscall\0A", 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $a0, 12 /* clobber */, implicit-def early-clobber $c3, 12 /* clobber */, implicit-def early-clobber $c4, 12 /* clobber */, implicit-def dead early-clobber $at
; MIR-NEXT:   $c4 = LOADCAP $zero_64, 0, $c11 :: (load (s128) from %stack.1)
; MIR-NEXT:   $c3 = LOADCAP $zero_64, 16, $c11 :: (load (s128) from %stack.0)
; MIR-NEXT:   renamable $v0 = CAPLOAD832 $zero_64, 0, killed renamable $c3 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $at = CAPLOAD832 $zero_64, 0, killed renamable $c4 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $v0, killed renamable $v1
; MIR-NEXT:   renamable $v0 = nsw ADDu killed renamable $at, killed renamable $v0
; MIR-NEXT:   $c11 = CIncOffsetImm $c11, 32
; MIR-NEXT:   PseudoReturnCap $c17 {
; MIR-NEXT:     $zero = SLL $zero, 0
; MIR-NEXT:   }
entry:
  tail call void asm sideeffect "syscall\0A", "~{$4},~{$c3},~{$c4},~{$1}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}
