; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/mempcpy.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs %s -o - -O2 | FileCheck %s

define ptr addrspace(200) @wrap_mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n) nounwind {
; CHECK-LABEL: wrap_mempcpy:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset $c11, $c11, -48
; CHECK-NEXT:    csd $16, $zero, 40($c11) # 8-byte Folded Spill
; CHECK-NEXT:    csc $c18, $zero, 16($c11) # 16-byte Folded Spill
; CHECK-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; CHECK-NEXT:    move $16, $4
; CHECK-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; CHECK-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; CHECK-NEXT:    cgetpccincoffset $c1, $1
; CHECK-NEXT:    clcbi $c12, %capcall20(memcpy)($c1)
; CHECK-NEXT:    cjalr $c12, $c17
; CHECK-NEXT:    cmove $c18, $c3
; CHECK-NEXT:    cincoffset $c3, $c18, $16
; CHECK-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; CHECK-NEXT:    clc $c18, $zero, 16($c11) # 16-byte Folded Reload
; CHECK-NEXT:    cld $16, $zero, 40($c11) # 8-byte Folded Reload
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c11, $c11, 48
  %1 = tail call ptr addrspace(200) @mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n)
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @mempcpy(ptr addrspace(200), ptr addrspace(200), i64)
