; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt -passes=instcombine -o - -S %s | FileCheck %s -check-prefix CHERI128
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n64-S128-A200-P200-G200"
target triple = "riscv64-unknown-freebsd"

%class.duration = type { i128 }

; Previously this input would result in an invalid ptrtoint instruction and a crash for CHERI128 (CHERI256 works fine)
; TODO: On CHERI we convert the memcpy to a i8 addrspace(200)* load/store which results in worse output assembly

define i128 @test2(ptr dereferenceable(16) %e) local_unnamed_addr nounwind {
; CHERI128-LABEL: define {{[^@]+}}@test2
; CHERI128-SAME: (ptr dereferenceable(16) [[E:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHERI128-NEXT:  entry:
; CHERI128-NEXT:    [[REF_TMP:%.*]] = alloca [[CLASS_DURATION:%.*]], align 16
; CHERI128-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[E]], align 16
; CHERI128-NEXT:    store ptr addrspace(200) [[TMP0]], ptr [[REF_TMP]], align 16
; CHERI128-NEXT:    [[CALL:%.*]] = call addrspace(200) i128 @_ZN8durationInE1fEv(ptr nonnull [[REF_TMP]]) #[[ATTR0]]
; CHERI128-NEXT:    ret i128 [[CALL]]
;
entry:
  %ref.tmp = alloca %class.duration, align 16
  call void @llvm.memcpy.p0.p0.i64(ptr align 16 %ref.tmp, ptr align 16 %e, i64 16, i1 false)
  %call = call i128 @_ZN8durationInE1fEv(ptr %ref.tmp)
  ret i128 %call
}

define i128 @_ZN8durationInE1fEv(ptr %h) {
; CHERI128-LABEL: define {{[^@]+}}@_ZN8durationInE1fEv
; CHERI128-SAME: (ptr [[H:%.*]]) addrspace(200) {
; CHERI128-NEXT:  entry:
; CHERI128-NEXT:    [[TMP0:%.*]] = load i128, ptr [[H]], align 16
; CHERI128-NEXT:    ret i128 [[TMP0]]
;
entry:
  %as = getelementptr %class.duration, ptr %h, i64 0, i32 0
  %0 = load i128, ptr %as, align 16
  ret i128 %0
}

declare void @llvm.memcpy.p0.p0.i64(ptr nocapture writeonly, ptr nocapture readonly, i64, i1)
declare void @llvm.lifetime.start.p0(i64, ptr)
declare void @llvm.lifetime.end.p0(i64, ptr)
