; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/bn_x931p-regression.ll
;; After a C13==NULL optimization in the MIPS backend,
;; openssl/crypto/bn/bn_x931p.c was failing.
;; Check that it works as expected
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP

declare i32 @b() addrspace(200)

; Calling a function with 9+ capability parameters would previously cause verification errors
define i32 @a(ptr addrspace(200) %0, ptr addrspace(200) %1, ptr addrspace(200) %2, ptr addrspace(200) %3, ptr addrspace(200) %4, ptr addrspace(200) %5, ptr addrspace(200) %6, ptr addrspace(200) %7, ptr addrspace(200) %8) addrspace(200) nounwind {
; PURECAP-LABEL: a:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    ccall b
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
  %ret = call i32 @b()
  ret i32 %ret
}
