; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/bzerocap.ll
;; This test assumes cheri128, since on 256 a 16 byte aligned pointer won't be expanded
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -O1 %s -o - | FileCheck %s --check-prefix=PURECAP

define void @zero64(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero64:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc zero, 56(a0)
; PURECAP-NEXT:    csc zero, 48(a0)
; PURECAP-NEXT:    csc zero, 40(a0)
; PURECAP-NEXT:    csc zero, 32(a0)
; PURECAP-NEXT:    csc zero, 24(a0)
; PURECAP-NEXT:    csc zero, 16(a0)
; PURECAP-NEXT:    csc zero, 8(a0)
; PURECAP-NEXT:    csc zero, 0(a0)
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 64, i1 false)
  ret void
}

define void @zero64_unaligned(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero64_unaligned:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc zero, 56(a0)
; PURECAP-NEXT:    csc zero, 48(a0)
; PURECAP-NEXT:    csc zero, 40(a0)
; PURECAP-NEXT:    csc zero, 32(a0)
; PURECAP-NEXT:    csc zero, 24(a0)
; PURECAP-NEXT:    csc zero, 16(a0)
; PURECAP-NEXT:    csc zero, 8(a0)
; PURECAP-NEXT:    csc zero, 0(a0)
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 8 %out, i8 0, i64 64, i1 false)
  ret void
}

define void @zero65(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero65:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 65
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 65, i1 false)
  ret void
}

define void @zero66(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero66:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 66
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 66, i1 false)
  ret void
}

define void @zero67(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero67:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 67
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 67, i1 false)
  ret void
}

define void @zero68(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero68:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 68
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 68, i1 false)
  ret void
}

define void @zero69(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero69:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 69
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 69, i1 false)
  ret void
}

define void @zero70(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero70:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 70
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 70, i1 false)
  ret void
}

define void @zero71(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero71:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 71
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 71, i1 false)
  ret void
}

define void @zero72(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero72:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 72
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 72, i1 false)
  ret void
}

define void @zero73(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero73:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 73
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 73, i1 false)
  ret void
}

define void @zero74(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero74:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 74
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 74, i1 false)
  ret void
}

define void @zero75(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero75:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 75
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 75, i1 false)
  ret void
}

define void @zero76(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero76:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 76
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 76, i1 false)
  ret void
}

define void @zero77(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero77:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 77
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 77, i1 false)
  ret void
}

define void @zero78(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero78:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 78
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 78, i1 false)
  ret void
}

define void @zero79(ptr addrspace(200) nocapture %out) local_unnamed_addr nounwind {
; PURECAP-LABEL: zero79:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    li a2, 79
; PURECAP-NEXT:    li a1, 0
; PURECAP-NEXT:    li a3, 0
; PURECAP-NEXT:    ccall memset
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 %out, i8 0, i64 79, i1 false)
  ret void
}

declare void @llvm.memset.p200.i64(ptr addrspace(200) nocapture writeonly, i8, i64, i1 immarg) #0

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: write) }
