; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/captable-global-func-ptrtoint-in-csetoffset.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP
; Check that we don't accidentally create a nonsense COPY node ($at_64 = COPY killed renamable $c1)
; when the result of the GlobalAddr goes through a ptrtoint

declare i32 @foo(ptr addrspace(200)) addrspace(200)

declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i32(ptr addrspace(200), i32) addrspace(200)

define void @main(ptr addrspace(200) %arg) addrspace(200) nounwind {
; PURECAP-LABEL: main:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -16
; PURECAP-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; PURECAP-NEXT:  .LBB0_1: # %entry
; PURECAP-NEXT:    # Label of block must be emitted
; PURECAP-NEXT:    auipcc a1, %got_pcrel_hi(foo)
; PURECAP-NEXT:    clc a1, %pcrel_lo(.LBB0_1)(a1)
; PURECAP-NEXT:    csetoffset a0, a0, a1
; PURECAP-NEXT:    cjalr a0
; PURECAP-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 16
; PURECAP-NEXT:    cret
entry:
  %0 = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i32(ptr addrspace(200) %arg, i32 ptrtoint (ptr addrspace(200) @foo to i32))
  %call3 = call i32 %0(ptr addrspace(200) undef)
  ret void
}
