; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-member-pointer.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -asm-verbose -verify-regalloc -O0 %s -o - | FileCheck %s
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -asm-verbose -verify-regalloc -O1 %s -o - | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -asm-verbose -verify-regalloc -O2 %s -o - | FileCheck %s --check-prefix=OPT

@global_func_ptr = external local_unnamed_addr addrspace(200) global ptr addrspace(200), align 32

; Function Attrs: nounwind
define i32 @func_ptr_dereference(ptr addrspace(200) %a, ptr addrspace(200) inreg %ptr.coerce0, i32 inreg %ptr.coerce1) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: func_ptr_dereference:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -32
; CHECK-NEXT:    csc a1, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    srai a1, a2, 1
; CHECK-NEXT:    cincoffset a0, a0, a1
; CHECK-NEXT:    csc a0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc a0, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    andi a0, a2, 1
; CHECK-NEXT:    beqz a0, .LBB0_2
; CHECK-NEXT:    j .LBB0_1
; CHECK-NEXT:  .LBB0_1: # %memptr.virtual
; CHECK-NEXT:    clc a1, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc a0, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc a0, 0(a0)
; CHECK-NEXT:    mv a1, a1
; CHECK-NEXT:    cincoffset a0, a0, a1
; CHECK-NEXT:    clc t1, 0(a0)
; CHECK-NEXT:    csc t1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_2: # %memptr.nonvirtual
; CHECK-NEXT:    clc t1, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    csc t1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_3: # %memptr.end
; CHECK-NEXT:    clc a0, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc t1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 32
; CHECK-NEXT:    cjr t1
;
; OPT-LABEL: func_ptr_dereference:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    srai a3, a2, 1
; OPT-NEXT:    andi a2, a2, 1
; OPT-NEXT:    cincoffset a0, a0, a3
; OPT-NEXT:    beqz a2, .LBB0_2
; OPT-NEXT:  # %bb.1: # %memptr.virtual
; OPT-NEXT:    clc a2, 0(a0)
; OPT-NEXT:    cincoffset a1, a2, a1
; OPT-NEXT:    clc a1, 0(a1)
; OPT-NEXT:  .LBB0_2: # %memptr.end
; OPT-NEXT:    cjr a1
entry:
  %memptr.adj.shifted = ashr i32 %ptr.coerce1, 1
  %this.not.adjusted = bitcast ptr addrspace(200) %a to ptr addrspace(200)
  %memptr.vtable.addr = getelementptr inbounds i8, ptr addrspace(200) %this.not.adjusted, i32 %memptr.adj.shifted
  %this.adjusted = bitcast ptr addrspace(200) %memptr.vtable.addr to ptr addrspace(200)
  %0 = and i32 %ptr.coerce1, 1
  %memptr.isvirtual = icmp eq i32 %0, 0
  br i1 %memptr.isvirtual, label %memptr.nonvirtual, label %memptr.virtual

memptr.virtual:                                   ; preds = %entry
  %1 = bitcast ptr addrspace(200) %memptr.vtable.addr to ptr addrspace(200)
  %vtable = load ptr addrspace(200), ptr addrspace(200) %1, align 32, !tbaa !2
  %memptr.vtable.offset = ptrtoint ptr addrspace(200) %ptr.coerce0 to i32
  %2 = getelementptr i8, ptr addrspace(200) %vtable, i32 %memptr.vtable.offset
  %3 = bitcast ptr addrspace(200) %2 to ptr addrspace(200)
  %memptr.virtualfn = load ptr addrspace(200), ptr addrspace(200) %3, align 32
  br label %memptr.end

memptr.nonvirtual:                                ; preds = %entry
  %memptr.nonvirtualfn = bitcast ptr addrspace(200) %ptr.coerce0 to ptr addrspace(200)
  br label %memptr.end

memptr.end:                                       ; preds = %memptr.nonvirtual, %memptr.virtual
  %4 = phi ptr addrspace(200) [ %memptr.virtualfn, %memptr.virtual ], [ %memptr.nonvirtualfn, %memptr.nonvirtual ]
  %call = tail call i32 %4(ptr addrspace(200) %this.adjusted) #0
  ret i32 %call
}

attributes #0 = { nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"PIC Level", i32 2}
!2 = !{!3, !3, i64 0}
!3 = !{!"vtable pointer", !4, i64 0}
!4 = !{!"Simple C++ TBAA"}
