; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-bitfield.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f %s -o - | FileCheck %s --check-prefix=PURECAP
; Test that we can correctly legalise i128 and generate pointer arithmetic that
; doesn't crash the compiler.

%struct.foo = type { i128 }

@x = internal addrspace(200) global %struct.foo zeroinitializer, align 8

; Function Attrs: noinline nounwind
define i32 @main(i32 signext %argc, ptr addrspace(200) %argv) #0 {
; PURECAP-LABEL: main:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset sp, sp, -32
; PURECAP-NEXT:    csc ra, 24(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    csc s0, 16(sp) # 8-byte Folded Spill
; PURECAP-NEXT:    cincoffset s0, sp, 32
; PURECAP-NEXT:    andi a2, sp, -32
; PURECAP-NEXT:    csetaddr sp, sp, a2
; PURECAP-NEXT:  .LBB0_1: # %entry
; PURECAP-NEXT:    # Label of block must be emitted
; PURECAP-NEXT:    auipcc a2, %got_pcrel_hi(x)
; PURECAP-NEXT:    clc a2, %pcrel_lo(.LBB0_1)(a2)
; PURECAP-NEXT:    clw a3, 0(a2)
; PURECAP-NEXT:    csw a0, 8(sp)
; PURECAP-NEXT:    csc a1, 0(sp)
; PURECAP-NEXT:    csw zero, 12(sp)
; PURECAP-NEXT:    andi a3, a3, 1
; PURECAP-NEXT:    addi a3, a3, 2
; PURECAP-NEXT:    csw a3, 0(a2)
; PURECAP-NEXT:    li a0, 0
; PURECAP-NEXT:    cincoffset sp, s0, -32
; PURECAP-NEXT:    clc ra, 24(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    clc s0, 16(sp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset sp, sp, 32
; PURECAP-NEXT:    cret
entry:
  %retval = alloca i32, align 4, addrspace(200)
  %argc.addr = alloca i32, align 4, addrspace(200)
  %argv.addr = alloca ptr addrspace(200), align 32, addrspace(200)
  store i32 0, ptr addrspace(200) %retval, align 4
  store i32 %argc, ptr addrspace(200) %argc.addr, align 4
  store ptr addrspace(200) %argv, ptr addrspace(200) %argv.addr, align 32
  %bf.load = load i128, ptr addrspace(200) @x, align 4
  %bf.clear = and i128 %bf.load, -4294967295
  %bf.set = or i128 %bf.clear, 2
  store i128 %bf.set, ptr addrspace(200) @x, align 4
  ret i32 0
}

attributes #0 = { noinline nounwind }

!llvm.module.flags = !{!0}

!0 = !{i32 8, !"PIC Level", i32 2}
