; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri128.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f -O2 -verify-machineinstrs %s -o - | FileCheck %s

@array = common global [2 x ptr addrspace(200)] zeroinitializer, align 8

;; Check that we convert the index to an offset by multiplying by the
;; capability size:
define ptr addrspace(200) @get(i32 signext %x) {
; CHECK-LABEL: get:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .Lpcrel_hi0:
; CHECK-NEXT:    auipc a1, %got_pcrel_hi(array)
; CHECK-NEXT:    lw a1, %pcrel_lo(.Lpcrel_hi0)(a1)
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    lc a0, 0(a0)
; CHECK-NEXT:    ret
entry:
  %idxprom = sext i32 %x to i64
  %arrayidx = getelementptr inbounds [2 x ptr addrspace(200)], ptr @array, i64 0, i64 %idxprom
  %0 = load ptr addrspace(200), ptr %arrayidx, align 8
  ret ptr addrspace(200) %0
}
