; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheriabi_machdep-issue228.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f -O2 -verify-machineinstrs -relocation-model=static %s -o - | FileCheck %s
; https://github.com/CTSRD-CHERI/llvm/issues/228

; Function Attrs: inlinehint nounwind
define void @CHERIABI_SYS_mknodat_fill_uap() nounwind {
; CHECK-LABEL: CHERIABI_SYS_mknodat_fill_uap:
; CHECK:       # %bb.0: # %cheriabi_fetch_syscall_arg.exit119
; CHECK-NEXT:    cgettag a0, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    and a0, a0, a0
; CHECK-NEXT:    sh a0, 0(a0)
cheriabi_fetch_syscall_arg.exit119:
  %0 = ptrtoint ptr addrspace(200) undef to i16
  store i16 %0, ptr undef, align 2
  unreachable
}

define void @CHERIABI_SYS_mknodat_fill_uap1() nounwind {
; CHECK-LABEL: CHERIABI_SYS_mknodat_fill_uap1:
; CHECK:       # %bb.0: # %cheriabi_fetch_syscall_arg.exit119
cheriabi_fetch_syscall_arg.exit119:
  %0 = getelementptr i8, ptr addrspace(200) null, i64 undef
  store ptr addrspace(200) %0, ptr undef, align 16
  unreachable
}

define void @CHERIABI_SYS_mknodat_fill_uap2(ptr addrspace(200) %arg) nounwind {
; CHECK-LABEL: CHERIABI_SYS_mknodat_fill_uap2:
; CHECK:       # %bb.0: # %cheriabi_fetch_syscall_arg.exit119
; CHECK-NEXT:    cgettag a1, a0
; CHECK-NEXT:    neg a1, a1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    sh a0, 0(a0)
cheriabi_fetch_syscall_arg.exit119:
  %0 = ptrtoint ptr addrspace(200) %arg to i16
  store i16 %0, ptr undef, align 2
  unreachable
}

define void @CHERIABI_SYS_mknodat_fill_uap3(ptr addrspace(200) %arg, ptr %ptr) nounwind {
; CHECK-LABEL: CHERIABI_SYS_mknodat_fill_uap3:
; CHECK:       # %bb.0: # %cheriabi_fetch_syscall_arg.exit119
; CHECK-NEXT:    cgettag a2, a0
; CHECK-NEXT:    neg a2, a2
; CHECK-NEXT:    and a0, a0, a2
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
cheriabi_fetch_syscall_arg.exit119:
  %0 = ptrtoint ptr addrspace(200) %arg to i16
  store i16 %0, ptr %ptr, align 2
  ret void
}
