; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-csetbounds-immediate.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=HYBRID

declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200), i32)

define ptr addrspace(200) @setBoundsUnknown(ptr addrspace(200) %c, i32 %bounds) nounwind {
; HYBRID-LABEL: setBoundsUnknown:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csetbounds a0, a0, a1
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %c, i32 %bounds)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstant1(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstant1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csetbounds a0, a0, 1
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %c, i32 1)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstantMaxImmediate(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantMaxImmediate:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csetbounds a0, a0, 2047
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %c, i32 2047)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstantTooBigForImm(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantTooBigForImm:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csetbounds a0, a0, 2048
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %c, i32 2048)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsNegative(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsNegative:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    li a1, -2
; HYBRID-NEXT:    csetbounds a0, a0, a1
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %c, i32 -2)
  ret ptr addrspace(200) %0
}
