; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-load.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f %s -o - | FileCheck %s --check-prefix=PURECAP

define zeroext i8 @loadFromPtr1U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr1U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lb.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    zext.b a0, a0
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr1U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clb a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    zext.b a0, a0
; PURECAP-NEXT:    cret
entry:
  %0 = load i8, ptr addrspace(200) %a, align 1
  %conv = zext i8 %0 to i32
  %add = add nsw i32 %conv, 12
  %conv1 = trunc i32 %add to i8
  ret i8 %conv1
}

define signext i8 @loadFromPtr1(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lb.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    slli a0, a0, 24
; HYBRID-NEXT:    srai a0, a0, 24
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clb a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    slli a0, a0, 24
; PURECAP-NEXT:    srai a0, a0, 24
; PURECAP-NEXT:    cret
entry:
  %0 = load i8, ptr addrspace(200) %a, align 1
  %conv2 = zext i8 %0 to i32
  %add = add nsw i32 %conv2, 12
  %conv1 = trunc i32 %add to i8
  ret i8 %conv1
}

define zeroext i16 @loadFromPtr2U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr2U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lh.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    slli a0, a0, 16
; HYBRID-NEXT:    srli a0, a0, 16
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr2U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clh a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    slli a0, a0, 16
; PURECAP-NEXT:    srli a0, a0, 16
; PURECAP-NEXT:    cret
entry:
  %0 = load i16, ptr addrspace(200) %a, align 2
  %conv = zext i16 %0 to i32
  %add = add nsw i32 %conv, 12
  %conv1 = trunc i32 %add to i16
  ret i16 %conv1
}

define signext i16 @loadFromPtr2(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr2:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lh.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    slli a0, a0, 16
; HYBRID-NEXT:    srai a0, a0, 16
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr2:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clh a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    slli a0, a0, 16
; PURECAP-NEXT:    srai a0, a0, 16
; PURECAP-NEXT:    cret
entry:
  %0 = load i16, ptr addrspace(200) %a, align 2
  %conv2 = zext i16 %0 to i32
  %add = add nsw i32 %conv2, 12
  %conv1 = trunc i32 %add to i16
  ret i16 %conv1
}

define i32 @loadFromPtr4U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr4U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lw.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr4U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    cret
entry:
  %0 = load i32, ptr addrspace(200) %a, align 4
  %add = add i32 %0, 12
  ret i32 %add
}

define i32 @loadFromPtr4(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr4:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lw.cap a0, (a0)
; HYBRID-NEXT:    addi a0, a0, 12
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr4:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw a0, 0(a0)
; PURECAP-NEXT:    addi a0, a0, 12
; PURECAP-NEXT:    cret
entry:
  %0 = load i32, ptr addrspace(200) %a, align 4
  %add = add nsw i32 %0, 12
  ret i32 %add
}

define i64 @loadFromPtr8U(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr8U:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lw.cap a1, (a0)
; HYBRID-NEXT:    cincoffset a0, a0, 4
; HYBRID-NEXT:    lw.cap a2, (a0)
; HYBRID-NEXT:    addi a0, a1, 12
; HYBRID-NEXT:    sltu a1, a0, a1
; HYBRID-NEXT:    add a1, a2, a1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr8U:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw a1, 0(a0)
; PURECAP-NEXT:    clw a2, 4(a0)
; PURECAP-NEXT:    addi a0, a1, 12
; PURECAP-NEXT:    sltu a1, a0, a1
; PURECAP-NEXT:    add a1, a2, a1
; PURECAP-NEXT:    cret
entry:
  %0 = load i64, ptr addrspace(200) %a, align 8
  %add = add i64 %0, 12
  ret i64 %add
}

define i64 @loadFromPtr8(ptr addrspace(200) nocapture %a) nounwind {
; HYBRID-LABEL: loadFromPtr8:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lw.cap a1, (a0)
; HYBRID-NEXT:    cincoffset a0, a0, 4
; HYBRID-NEXT:    lw.cap a2, (a0)
; HYBRID-NEXT:    addi a0, a1, 12
; HYBRID-NEXT:    sltu a1, a0, a1
; HYBRID-NEXT:    add a1, a2, a1
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: loadFromPtr8:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    clw a1, 0(a0)
; PURECAP-NEXT:    clw a2, 4(a0)
; PURECAP-NEXT:    addi a0, a1, 12
; PURECAP-NEXT:    sltu a1, a0, a1
; PURECAP-NEXT:    add a1, a2, a1
; PURECAP-NEXT:    cret
entry:
  %0 = load i64, ptr addrspace(200) %a, align 8
  %add = add nsw i64 %0, 12
  ret i64 %add
}
