; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-cap-store.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f %s -o - | FileCheck %s --check-prefix=PURECAP

define void @storeToPtr1(ptr addrspace(200) nocapture %a, i8 signext %v) nounwind {
; HYBRID-LABEL: storeToPtr1:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    sb.cap a1, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: storeToPtr1:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csb a1, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store i8 %v, ptr addrspace(200) %a, align 1
  ret void
}

define void @storeToPtr2(ptr addrspace(200) nocapture %a, i16 signext %v) nounwind {
; HYBRID-LABEL: storeToPtr2:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    sh.cap a1, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: storeToPtr2:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csh a1, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store i16 %v, ptr addrspace(200) %a, align 2
  ret void
}

define void @storeToPtr4(ptr addrspace(200) nocapture %a, i32 %v) nounwind {
; HYBRID-LABEL: storeToPtr4:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    sw.cap a1, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: storeToPtr4:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csw a1, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store i32 %v, ptr addrspace(200) %a, align 4
  ret void
}

define void @storeToPtr8(ptr addrspace(200) nocapture %a, i64 %v) nounwind {
; HYBRID-LABEL: storeToPtr8:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    sw.cap a1, (a0)
; HYBRID-NEXT:    cincoffset a0, a0, 4
; HYBRID-NEXT:    sw.cap a2, (a0)
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: storeToPtr8:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csw a2, 4(a0)
; PURECAP-NEXT:    csw a1, 0(a0)
; PURECAP-NEXT:    cret
entry:
  store i64 %v, ptr addrspace(200) %a, align 8
  ret void
}
