; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-byval-argument-hybrid.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=HYBRID
%struct.arg_1000_long = type { [1000 x i64] }
%struct.arg_1000___intcap_t = type { [1000 x ptr addrspace(200)] }

@global_1000_long_struct = common global %struct.arg_1000_long zeroinitializer, align 8
@global_1000___intcap_t_struct = common global %struct.arg_1000___intcap_t zeroinitializer, align 16

; Function Attrs: nounwind
define void @call_1000_long_byval() local_unnamed_addr #0 {
; HYBRID-LABEL: call_1000_long_byval:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -2032
; HYBRID-NEXT:    sw ra, 2028(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    lui a0, 1
; HYBRID-NEXT:    addi a0, a0, 1888
; HYBRID-NEXT:    sub sp, sp, a0
; HYBRID-NEXT:  .Lpcrel_hi0:
; HYBRID-NEXT:    auipc a0, %got_pcrel_hi(global_1000_long_struct)
; HYBRID-NEXT:    lw a1, %pcrel_lo(.Lpcrel_hi0)(a0)
; HYBRID-NEXT:    lui a2, 2
; HYBRID-NEXT:    addi a2, a2, -192
; HYBRID-NEXT:    addi a0, sp, 8
; HYBRID-NEXT:    call memcpy
; HYBRID-NEXT:    addi a0, sp, 8
; HYBRID-NEXT:    call take_1000_long_byval
; HYBRID-NEXT:    lui a0, 1
; HYBRID-NEXT:    addi a0, a0, 1888
; HYBRID-NEXT:    add sp, sp, a0
; HYBRID-NEXT:    lw ra, 2028(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 2032
; HYBRID-NEXT:    ret
entry:
  tail call void @take_1000_long_byval(ptr nonnull byval(%struct.arg_1000_long) align 8 @global_1000_long_struct) #0
  ret void
}

declare void @other_func(ptr) local_unnamed_addr #0

declare void @take_1000_long_byval(ptr byval(%struct.arg_1000_long) align 8) local_unnamed_addr #0

; Function Attrs: nounwind
define void @call_1000___intcap_t_byval() local_unnamed_addr #0 {
; HYBRID-LABEL: call_1000___intcap_t_byval:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -2032
; HYBRID-NEXT:    sw ra, 2028(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    lui a0, 1
; HYBRID-NEXT:    addi a0, a0, 1904
; HYBRID-NEXT:    sub sp, sp, a0
; HYBRID-NEXT:  .Lpcrel_hi1:
; HYBRID-NEXT:    auipc a0, %got_pcrel_hi(global_1000___intcap_t_struct)
; HYBRID-NEXT:    lw a1, %pcrel_lo(.Lpcrel_hi1)(a0)
; HYBRID-NEXT:    lui a2, 2
; HYBRID-NEXT:    addi a2, a2, -192
; HYBRID-NEXT:    addi a0, sp, 16
; HYBRID-NEXT:    call memcpy
; HYBRID-NEXT:    addi a0, sp, 16
; HYBRID-NEXT:    call take_1000___intcap_t_byval
; HYBRID-NEXT:    lui a0, 1
; HYBRID-NEXT:    addi a0, a0, 1904
; HYBRID-NEXT:    add sp, sp, a0
; HYBRID-NEXT:    lw ra, 2028(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 2032
; HYBRID-NEXT:    ret
entry:
  tail call void @take_1000___intcap_t_byval(ptr nonnull byval(%struct.arg_1000___intcap_t) align 16 @global_1000___intcap_t_struct) #0
  ret void
}

declare void @take_1000___intcap_t_byval(ptr byval(%struct.arg_1000___intcap_t) align 16) local_unnamed_addr #0

attributes #0 = { nounwind }
