; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/inline-asm-clobber.ll
; CHERI-GENERIC-UTC: mir
; CHERI-GENERIC-UTC: llc
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs -o - -O0 %s -stop-after=instruction-select | FileCheck %s -check-prefix MIR
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs -o - -O3 %s | FileCheck %s -enable-var-scope
;
; https://github.com/CTSRD-CHERI/llvm/issues/274
;
; Source code:
; int test(int intval, const char* ptrval) {
;   __asm__ ("syscall\n"
;   :
;   :
;   : "a0", "$c3");
;   char x = *((volatile char*)ptrval);
;   return (int)x + intval;
; }
;
; The capability clobber registers were previously off by one: -> $c3 would save $c4, etc.

define i32 @test_clobber_c2(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mv a4, a0
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ecall
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb a0, 0(a1)
; CHECK-NEXT:    clb a1, 0(a2)
; CHECK-NEXT:    add a0, a0, a4
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    cret
; MIR-LABEL: name: test_clobber_c2
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10, $x11_y, $x12_y
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $x2_y = frame-setup CIncOffsetImm $x2_y, -16
; MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; MIR-NEXT:   CSC_64 $x12_y, $x2_y, 8 :: (store (s64) into %stack.0)
; MIR-NEXT:   $x12 = ADDI killed $x10, 0
; MIR-NEXT:   INLINEASM &ecall, 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $x10, 12 /* clobber */, implicit-def dead early-clobber $x13_y, 12 /* clobber */, implicit-def dead early-clobber $x5_y
; MIR-NEXT:   $x10_y = CLC_64 $x2_y, 8 :: (load (s64) from %stack.0)
; MIR-NEXT:   renamable $x11 = CLB killed renamable $x11_y, 0 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $x10 = CLB killed renamable $x10_y, 0 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $x11 = nsw ADD killed renamable $x11, killed renamable $x12
; MIR-NEXT:   renamable $x10 = nsw ADD killed renamable $x10, killed renamable $x11
; MIR-NEXT:   $x2_y = frame-destroy CIncOffsetImm $x2_y, 16
; MIR-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 0
; MIR-NEXT:   PseudoCRET implicit killed $x10
entry:
  tail call void asm sideeffect "ecall", "~{a0},~{ca3},~{ct0}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c3(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove a3, a1
; CHECK-NEXT:    mv a4, a0
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ecall
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb a0, 0(a3)
; CHECK-NEXT:    clb a1, 0(a2)
; CHECK-NEXT:    add a0, a0, a4
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    cret
; MIR-LABEL: name: test_clobber_c3
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10, $x11_y, $x12_y
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $x2_y = frame-setup CIncOffsetImm $x2_y, -16
; MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; MIR-NEXT:   CSC_64 $x12_y, $x2_y, 8 :: (store (s64) into %stack.0)
; MIR-NEXT:   CSC_64 $x11_y, $x2_y, 0 :: (store (s64) into %stack.1)
; MIR-NEXT:   $x12 = ADDI killed $x10, 0
; MIR-NEXT:   INLINEASM &ecall, 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $x10, 12 /* clobber */, implicit-def dead early-clobber $x11_y, 12 /* clobber */, implicit-def dead early-clobber $x5_y
; MIR-NEXT:   $x11_y = CLC_64 $x2_y, 0 :: (load (s64) from %stack.1)
; MIR-NEXT:   $x10_y = CLC_64 $x2_y, 8 :: (load (s64) from %stack.0)
; MIR-NEXT:   renamable $x11 = CLB killed renamable $x11_y, 0 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $x10 = CLB killed renamable $x10_y, 0 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $x11 = nsw ADD killed renamable $x11, killed renamable $x12
; MIR-NEXT:   renamable $x10 = nsw ADD killed renamable $x10, killed renamable $x11
; MIR-NEXT:   $x2_y = frame-destroy CIncOffsetImm $x2_y, 16
; MIR-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 0
; MIR-NEXT:   PseudoCRET implicit killed $x10
entry:
  tail call void asm sideeffect "ecall", "~{a0},~{ca1},~{ct0}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c4(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove a3, a2
; CHECK-NEXT:    mv a4, a0
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ecall
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb a0, 0(a1)
; CHECK-NEXT:    clb a1, 0(a3)
; CHECK-NEXT:    add a0, a0, a4
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    cret
; MIR-LABEL: name: test_clobber_c4
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10, $x11_y, $x12_y
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $x2_y = frame-setup CIncOffsetImm $x2_y, -16
; MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 16
; MIR-NEXT:   CSC_64 $x12_y, $x2_y, 8 :: (store (s64) into %stack.0)
; MIR-NEXT:   CSW $x10, $x2_y, 4 :: (store (s32) into %stack.1)
; MIR-NEXT:   INLINEASM &ecall, 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $x10, 12 /* clobber */, implicit-def dead early-clobber $x12_y, 12 /* clobber */, implicit-def dead early-clobber $x5_y
; MIR-NEXT:   $x12 = CLW $x2_y, 4 :: (load (s32) from %stack.1)
; MIR-NEXT:   $x10_y = CLC_64 $x2_y, 8 :: (load (s64) from %stack.0)
; MIR-NEXT:   renamable $x11 = CLB killed renamable $x11_y, 0 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $x10 = CLB killed renamable $x10_y, 0 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $x11 = nsw ADD killed renamable $x11, killed renamable $x12
; MIR-NEXT:   renamable $x10 = nsw ADD killed renamable $x10, killed renamable $x11
; MIR-NEXT:   $x2_y = frame-destroy CIncOffsetImm $x2_y, 16
; MIR-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 0
; MIR-NEXT:   PseudoCRET implicit killed $x10
entry:
  tail call void asm sideeffect "ecall", "~{a0},~{ca2},~{ct0}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}

define i32 @test_clobber_c3_c4(i32 signext %intval, ptr addrspace(200) %ptrval, ptr addrspace(200) %ptrval2) local_unnamed_addr {
; CHECK-LABEL: test_clobber_c3_c4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmove a3, a2
; CHECK-NEXT:    cmove a4, a1
; CHECK-NEXT:    mv a5, a0
; CHECK-NEXT:    #APP
; CHECK-NEXT:    ecall
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    clb a0, 0(a4)
; CHECK-NEXT:    clb a1, 0(a3)
; CHECK-NEXT:    add a0, a0, a5
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    cret
; MIR-LABEL: name: test_clobber_c3_c4
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10, $x11_y, $x12_y
; MIR-NEXT: {{  $}}
; MIR-NEXT:   $x2_y = frame-setup CIncOffsetImm $x2_y, -32
; MIR-NEXT:   frame-setup CFI_INSTRUCTION def_cfa_offset 32
; MIR-NEXT:   CSC_64 $x12_y, $x2_y, 24 :: (store (s64) into %stack.0)
; MIR-NEXT:   CSC_64 $x11_y, $x2_y, 16 :: (store (s64) into %stack.1)
; MIR-NEXT:   CSW $x10, $x2_y, 12 :: (store (s32) into %stack.2)
; MIR-NEXT:   INLINEASM &ecall, 1 /* sideeffect attdialect */, 12 /* clobber */, implicit-def dead early-clobber $x10, 12 /* clobber */, implicit-def dead early-clobber $x11_y, 12 /* clobber */, implicit-def dead early-clobber $x12_y, 12 /* clobber */, implicit-def dead early-clobber $x5_y
; MIR-NEXT:   $x12 = CLW $x2_y, 12 :: (load (s32) from %stack.2)
; MIR-NEXT:   $x11_y = CLC_64 $x2_y, 16 :: (load (s64) from %stack.1)
; MIR-NEXT:   $x10_y = CLC_64 $x2_y, 24 :: (load (s64) from %stack.0)
; MIR-NEXT:   renamable $x11 = CLB killed renamable $x11_y, 0 :: (volatile load (s8) from %ir.ptrval, addrspace 200)
; MIR-NEXT:   renamable $x10 = CLB killed renamable $x10_y, 0 :: (volatile load (s8) from %ir.ptrval2, addrspace 200)
; MIR-NEXT:   renamable $x11 = nsw ADD killed renamable $x11, killed renamable $x12
; MIR-NEXT:   renamable $x10 = nsw ADD killed renamable $x10, killed renamable $x11
; MIR-NEXT:   $x2_y = frame-destroy CIncOffsetImm $x2_y, 32
; MIR-NEXT:   frame-destroy CFI_INSTRUCTION def_cfa_offset 0
; MIR-NEXT:   PseudoCRET implicit killed $x10
entry:
  tail call void asm sideeffect "ecall", "~{a0},~{ca1},~{ca2},~{ct0}"()
  %0 = load volatile i8, ptr addrspace(200) %ptrval, align 1
  %1 = load volatile i8, ptr addrspace(200) %ptrval2, align 1
  %conv = sext i8 %0 to i32
  %conv2 = sext i8 %1 to i32
  %add = add nsw i32 %conv, %intval
  %add2 = add nsw i32 %conv2, %add
  ret i32 %add2
}
