; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/int128.ll
; See clang/test/CodeGen/cheri/libcxx-filesystem-crash.cpp
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs < %s | FileCheck %s -check-prefixes CHECK

declare void @llvm.lifetime.start.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)
declare void @llvm.lifetime.end.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)

define i128 @test2(ptr addrspace(200) nocapture readonly dereferenceable(16) %e) local_unnamed_addr addrspace(200) {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    clc a1, 0(a1)
; CHECK-NEXT:    cincoffset a2, sp, 0
; CHECK-NEXT:    csetbounds a2, a2, 8
; CHECK-NEXT:    csc a1, 0(sp)
; CHECK-NEXT:    clw a1, 12(a2)
; CHECK-NEXT:    clw a3, 8(a2)
; CHECK-NEXT:    clw a4, 4(a2)
; CHECK-NEXT:    clw a2, 0(a2)
; CHECK-NEXT:    csw a1, 12(a0)
; CHECK-NEXT:    csw a3, 8(a0)
; CHECK-NEXT:    csw a4, 4(a0)
; CHECK-NEXT:    csw a2, 0(a0)
; CHECK-NEXT:    cincoffset sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    cret
entry:
  %ref.tmp.sroa.0 = alloca ptr addrspace(200), align 16, addrspace(200)
  %tmpcast = bitcast ptr addrspace(200) %ref.tmp.sroa.0 to ptr addrspace(200)
  %ref.tmp.sroa.0.0..sroa_cast4 = bitcast ptr addrspace(200) %ref.tmp.sroa.0 to ptr addrspace(200)
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) nonnull %ref.tmp.sroa.0.0..sroa_cast4)
  %0 = bitcast ptr addrspace(200) %e to ptr addrspace(200)
  %1 = load ptr addrspace(200), ptr addrspace(200) %0, align 16
  store ptr addrspace(200) %1, ptr addrspace(200) %ref.tmp.sroa.0, align 16
  %ref.tmp.sroa.0.0.ref.tmp.sroa.0.0. = load i128, ptr addrspace(200) %tmpcast, align 16
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %ref.tmp.sroa.0.0..sroa_cast4)
  ret i128 %ref.tmp.sroa.0.0.ref.tmp.sroa.0.0.
}
