; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/mempcpy.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs %s -o - -O2 | FileCheck %s

define ptr addrspace(200) @wrap_mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n) nounwind {
; CHECK-LABEL: wrap_mempcpy:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctail mempcpy
  %1 = tail call ptr addrspace(200) @mempcpy(ptr addrspace(200) %dst, ptr addrspace(200) %src, i64 %n)
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @mempcpy(ptr addrspace(200), ptr addrspace(200), i64)
