; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/rust.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs %s -o - | FileCheck %s

;; Crash found while compiling rust-generated code:
declare { ptr addrspace(200), ptr addrspace(200), ptr addrspace(200) } @"_ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE"(ptr addrspace(200), i128) addrspace(200)

define void @a() nounwind {
; CHECK-LABEL: a:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset sp, sp, -48
; CHECK-NEXT:    csc ra, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csw zero, 12(sp)
; CHECK-NEXT:    csw zero, 8(sp)
; CHECK-NEXT:    csw zero, 4(sp)
; CHECK-NEXT:    li a1, 6
; CHECK-NEXT:    cincoffset a0, sp, 16
; CHECK-NEXT:    cincoffset a2, sp, 0
; CHECK-NEXT:    csw a1, 0(sp)
; CHECK-NEXT:    cmove a1, zero
; CHECK-NEXT:    ccall _ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE
; CHECK-NEXT:    clc ra, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 48
; CHECK-NEXT:    cret
  %1 = call { ptr addrspace(200), ptr addrspace(200), ptr addrspace(200) } @"_ZN13libcore_cheri5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$4iter17h36a7eda044ca512cE"(ptr addrspace(200) null, i128 6)
  ret void
}
