; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/store-inttoptr-minus-one.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -verify-machineinstrs %s -o - | FileCheck %s

@global_minus_1 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (i32 -1 to ptr addrspace(200)), align 32
@global_minus_10 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (i32 -10 to ptr addrspace(200)), align 32
@global_123456 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (i32 123456 to ptr addrspace(200)), align 32
@b = common local_unnamed_addr addrspace(200) global ptr addrspace(200) null, align 32

define void @c() local_unnamed_addr addrspace(200) noinline nounwind {
; CHECK-LABEL: c:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB0_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(b)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB0_1)(a0)
; CHECK-NEXT:    cincoffset a1, zero, -1
; CHECK-NEXT:    csc a1, 0(a0)
; CHECK-NEXT:    cret
entry:
  store ptr addrspace(200) inttoptr (i32 -1 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

define void @d() local_unnamed_addr addrspace(200) noinline nounwind {
; CHECK-LABEL: d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB1_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(b)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB1_1)(a0)
; CHECK-NEXT:    csc zero, 0(a0)
; CHECK-NEXT:    cret
entry:
  store ptr addrspace(200) null, ptr addrspace(200) @b, align 32
  ret void
}

define void @e() local_unnamed_addr addrspace(200) noinline nounwind {
; CHECK-LABEL: e:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB2_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(b)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB2_1)(a0)
; CHECK-NEXT:    cincoffset a1, zero, 1
; CHECK-NEXT:    csc a1, 0(a0)
; CHECK-NEXT:    cret
entry:
  store ptr addrspace(200) inttoptr (i32 1 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

define void @f() local_unnamed_addr addrspace(200) noinline nounwind {
; CHECK-LABEL: f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB3_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(b)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB3_1)(a0)
; CHECK-NEXT:    lui a1, 30
; CHECK-NEXT:    addi a1, a1, 576
; CHECK-NEXT:    cincoffset a1, zero, a1
; CHECK-NEXT:    csc a1, 0(a0)
; CHECK-NEXT:    cret
entry:
  store ptr addrspace(200) inttoptr (i32 123456 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

; UTC_ARGS: --disable
; CHECK-LABEL: global_minus_1:
; CHECK-NEXT:  .chericap	4294967295
; CHECK-NEXT:  .size	global_minus_1, 8
; CHECK-LABEL: global_minus_10:
; CHECK-NEXT:  .chericap	4294967286
; CHECK-NEXT:  .size	global_minus_10, 8
; CHECK-LABEL: global_123456:
; CHECK-NEXT:  .chericap	123456
; CHECK-NEXT:  .size	global_123456, 8
