; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: %riscv32_cheri_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=IL32PC64 %s
; RUN: %riscv64_cheri_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=L64PC128 %s

;; RV CHERI's cincoffset has a 12-bit signed immediate field (range
;; [-2048, +2047]). The four functions below probe that boundary.

define ptr addrspace(200) @imm(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; IL32PC64-LABEL: imm:
; IL32PC64:       # %bb.0: # %entry
; IL32PC64-NEXT:    cincoffset a0, a0, 2047
; IL32PC64-NEXT:    cret
;
; L64PC128-LABEL: imm:
; L64PC128:       # %bb.0: # %entry
; L64PC128-NEXT:    cincoffset a0, a0, 2047
; L64PC128-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 2047
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @imm1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; IL32PC64-LABEL: imm1:
; IL32PC64:       # %bb.0: # %entry
; IL32PC64-NEXT:    cincoffset a0, a0, -2048
; IL32PC64-NEXT:    cret
;
; L64PC128-LABEL: imm1:
; L64PC128:       # %bb.0: # %entry
; L64PC128-NEXT:    cincoffset a0, a0, -2048
; L64PC128-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -2048
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; IL32PC64-LABEL: reg:
; IL32PC64:       # %bb.0: # %entry
; IL32PC64-NEXT:    li a1, 1
; IL32PC64-NEXT:    slli a1, a1, 11
; IL32PC64-NEXT:    cincoffset a0, a0, a1
; IL32PC64-NEXT:    cret
;
; L64PC128-LABEL: reg:
; L64PC128:       # %bb.0: # %entry
; L64PC128-NEXT:    li a1, 1
; L64PC128-NEXT:    slli a1, a1, 11
; L64PC128-NEXT:    cincoffset a0, a0, a1
; L64PC128-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 2048
  ret ptr addrspace(200) %add.ptr
}

define ptr addrspace(200) @reg1(ptr addrspace(200) readnone %a) local_unnamed_addr nounwind {
; IL32PC64-LABEL: reg1:
; IL32PC64:       # %bb.0: # %entry
; IL32PC64-NEXT:    lui a1, 1048575
; IL32PC64-NEXT:    addi a1, a1, 2047
; IL32PC64-NEXT:    cincoffset a0, a0, a1
; IL32PC64-NEXT:    cret
;
; L64PC128-LABEL: reg1:
; L64PC128:       # %bb.0: # %entry
; L64PC128-NEXT:    lui a1, 1048575
; L64PC128-NEXT:    addi a1, a1, 2047
; L64PC128-NEXT:    cincoffset a0, a0, a1
; L64PC128-NEXT:    cret
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -2049
  ret ptr addrspace(200) %add.ptr
}
