; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: %riscv64_cheri_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=HYBRID %s

declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200), i64)

define ptr addrspace(200) @setBoundsConstantMaxImmediate(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantMaxImmediate:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csetbounds a0, a0, 4095
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 4095)
  ret ptr addrspace(200) %0
}

define ptr addrspace(200) @setBoundsConstantTooBigForImm(ptr addrspace(200) %c) nounwind {
; HYBRID-LABEL: setBoundsConstantTooBigForImm:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    lui a1, 1
; HYBRID-NEXT:    csetbounds a0, a0, a1
; HYBRID-NEXT:    ret
entry:
  %0 = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %c, i64 4096)
  ret ptr addrspace(200) %0
}
