; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64_cheri_llc %s -o - | FileCheck %s -check-prefixes CHECK,HYBRID
; RUN: %riscv64_cheri_purecap_llc %s -o - | FileCheck %s -check-prefixes CHECK,PURECAP
; ModuleID = '/Users/alex/cheri/llvm-project/clang/test/Sema/cheri/strtol-regression.c'
; This previously crashed due to the use of getPointerTy instead of getPointerRangeTy

define void @b(i8 %a) local_unnamed_addr addrspace(200) {
; HYBRID-LABEL: b:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    zext.b a0, a0
; HYBRID-NEXT:    addi a0, a0, -65
; HYBRID-NEXT:    li a1, 37
; HYBRID-NEXT:    bltu a1, a0, .LBB0_2
; HYBRID-NEXT:  # %bb.1: # %entry
; HYBRID-NEXT:    li a1, 63
; HYBRID-NEXT:    slli a1, a1, 32
; HYBRID-NEXT:    addi a1, a1, 63
; HYBRID-NEXT:    srl a0, a1, a0
; HYBRID-NEXT:    andi a0, a0, 1
; HYBRID-NEXT:    bnez a0, .LBB0_3
; HYBRID-NEXT:  .LBB0_2: # %if.end
; HYBRID-NEXT:    ret
; HYBRID-NEXT:  .LBB0_3: # %for.cond.preheader
;
; PURECAP-LABEL: b:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    zext.b a0, a0
; PURECAP-NEXT:    addi a0, a0, -65
; PURECAP-NEXT:    li a1, 37
; PURECAP-NEXT:    bltu a1, a0, .LBB0_2
; PURECAP-NEXT:  # %bb.1: # %entry
; PURECAP-NEXT:    li a1, 63
; PURECAP-NEXT:    slli a1, a1, 32
; PURECAP-NEXT:    addi a1, a1, 63
; PURECAP-NEXT:    srl a0, a1, a0
; PURECAP-NEXT:    andi a0, a0, 1
; PURECAP-NEXT:    bnez a0, .LBB0_3
; PURECAP-NEXT:  .LBB0_2: # %if.end
; PURECAP-NEXT:    cret
; PURECAP-NEXT:  .LBB0_3: # %for.cond.preheader
entry:
  switch i8 %a, label %if.end [
    i8 102, label %for.cond.preheader
    i8 101, label %for.cond.preheader
    i8 100, label %for.cond.preheader
    i8 99, label %for.cond.preheader
    i8 98, label %for.cond.preheader
    i8 97, label %for.cond.preheader
    i8 70, label %for.cond.preheader
    i8 69, label %for.cond.preheader
    i8 68, label %for.cond.preheader
    i8 67, label %for.cond.preheader
    i8 66, label %for.cond.preheader
    i8 65, label %for.cond.preheader
  ]

for.cond.preheader:                               ; preds = %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry
  unreachable

if.end:                                           ; preds = %entry
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
