; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc @PURECAP_HARDFLOAT_ARGS@ -verify-machineinstrs %s -o - | FileCheck %s

@global_minus_1 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (iCAPRANGE -1 to ptr addrspace(200)), align 32
@global_minus_10 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (iCAPRANGE -10 to ptr addrspace(200)), align 32
@global_123456 = local_unnamed_addr addrspace(200) global ptr addrspace(200) inttoptr (iCAPRANGE 123456 to ptr addrspace(200)), align 32
@b = common local_unnamed_addr addrspace(200) global ptr addrspace(200) null, align 32

define void @c() local_unnamed_addr addrspace(200) noinline nounwind {
entry:
  store ptr addrspace(200) inttoptr (iCAPRANGE -1 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

define void @d() local_unnamed_addr addrspace(200) noinline nounwind {
entry:
  store ptr addrspace(200) null, ptr addrspace(200) @b, align 32
  ret void
}

define void @e() local_unnamed_addr addrspace(200) noinline nounwind {
entry:
  store ptr addrspace(200) inttoptr (iCAPRANGE 1 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

define void @f() local_unnamed_addr addrspace(200) noinline nounwind {
entry:
  store ptr addrspace(200) inttoptr (iCAPRANGE 123456 to ptr addrspace(200)), ptr addrspace(200) @b, align 32
  ret void
}

; UTC_ARGS: --disable
; CHECK-LABEL: global_minus_1:
@IFNOT-RISCV32@; CHECK-NEXT:  .chericap	-1
@IF-RISCV32@; CHECK-NEXT:  .chericap	4294967295
; CHECK-NEXT:  .size	global_minus_1, @CAP_BYTES@
; CHECK-LABEL: global_minus_10:
@IFNOT-RISCV32@; CHECK-NEXT:  .chericap	-10
@IF-RISCV32@; CHECK-NEXT:  .chericap	4294967286
; CHECK-NEXT:  .size	global_minus_10, @CAP_BYTES@
; CHECK-LABEL: global_123456:
; CHECK-NEXT:  .chericap	123456
; CHECK-NEXT:  .size	global_123456, @CAP_BYTES@
