name: Release builds

on:
  push:
    branches:
      - cheriot
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Build and upload artefact ${{ matrix.arch }}
    runs-on: "cirun-gcp-${{ matrix.arch }}--${{ github.run_id }}"
    timeout-minutes: 120

    strategy:
      matrix:
        include:
          - arch: x86
          - arch: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          set -eo pipefail
          sudo apt-get update
          sudo apt-get install -y clang ninja-build lld cmake ccache

      - name: Configure
        run: |
          mkdir Build
          cd Build
          cmake ../llvm \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb" \
            -DLLVM_ENABLE_UNWIND_TABLES=NO \
            -DLLVM_ENABLE_LLD=ON \
            -DLLVM_TARGETS_TO_BUILD=RISCV \
            -DLLVM_DISTRIBUTION_COMPONENTS="clang;clangd;lld;llvm-objdump;llvm-objcopy;llvm-strip;llvm-readelf;clang-tidy;clang-format;lldb;liblldb" \
            -DCMAKE_INSTALL_PREFIX=install \
            -DLLVM_PARALLEL_LINK_JOBS=1 \
            -DLLVM_APPEND_VC_REV=ON \
            -DLLVM_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_FORCE_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_VC_REVISION=${{ github.sha }} \
            -DLLVM_CCACHE_BUILD=OFF \
            -G Ninja

      - name: Build
        env:
          NINJA_STATUS: "%p [%f:%s/%t] %o/s, %es: "
        run: |
          cd Build
          ninja install-distribution
          cp ../llvm/LICENSE.TXT install/LLVM-LICENSE.TXT
          # Artefact upload uploads symlinks as copies, so delete all of the clang symlinks
          rm install/bin/clang
          rm install/bin/clang++
          rm install/bin/clang-cl
          rm install/bin/clang-cpp
          rm install/bin/ld.lld
          rm install/bin/ld64*
          rm install/bin/lld-link
          rm install/bin/wasm-ld
          find install/lib -maxdepth 1 -type l -delete

      - name: Upload artefact
        uses: actions/upload-artifact@v7
        with:
          name: llvm-${{ matrix.arch }}
          path: Build/install/**